### ISSUE TITLE
Document which scopes are necessary

### ISSUE THREAD

**Issue by kevinburke** [michenriksen/gitrob#1]
Would be nice if the README or the tool told you which scopes you needed to enable for the access token to work.

**Comment by jfalken** [comment]
I was able to get this to work by only allowing `public_repo` and `read:org` permissions to the access token.

**Comment by michenriksen** [comment]
That is a good point. If you just want to check what is publicly available, it should be possible to actually uncheck all scopes, so that it just becomes a public access token. The tokens are mostly needed to avoid running into rate limiting.

I'll update the README with your suggestion.

**Comment by mikeatlas** [comment]
+1

**Comment by BillWeiss** [comment]
:+1: , for what it's worth.

**Comment by maxvt** [comment]
public_repo was enough for me

**Comment by michenriksen** [comment]
This is now documented in the README.

**Comment by frewsxcv** [comment]
It doesn't look like this is documented anymore – maybe it should be readded?

**Comment by nadavoosh** [comment]
This information seems to have disappeared from the readme.
