### ISSUE TITLE
Sequel::DatabaseConnectionError

### ISSUE THREAD

**Issue by mattsibley** [michenriksen/gitrob#100]
Hi any anyone help me with this error?

___|_| |_ ___ ___| |_
| . | |  _|  _| . | . |
|_  |_|_| |_| |___|___|
|___| By @michenriksen

[*] Starting Gitrob version 1.1.0 at 2017-01-21 16:01 GMT
[*] Loading configuration... done
[*] Preparing database... failed
[!] Sequel::DatabaseConnectionError: PG::ConnectionBad: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

I tried to open the port 5432 in Kali using

:~# iptables -A INPUT -p tcp -s 0/0 --sport 1024:65535 -d 202.54.1.20 --dport 5432 -m state --state NEW,ESTABLISHED -j ACCEPT

and 

iptables -A OUTPUT -p tcp -s 127.0.0.1  --sport 5432 -d 0/0 --dport 1024:65535 -m state --state ESTABLISHED -j ACCEPT

but no joy still failing to connect to database (feeding it the correct user name and password for the gitrob postgresql database).

Thanks

Matt

**Comment by michenriksen** [comment]
Hi, Postgresql is not started as default in Kali, you'll need to execute `service postgresql start` to start it up. I think that should fix your issue.

**Comment by dmatrix500** [comment]
hi ,@michenriksen  This fixed the issue . This is a great tool . Many Thanx .

**Comment by arbazkiraak** [comment]
root@kali:/usr/local/bin# gitrob configure
     _ _           _
 ___|_| |_ ___ ___| |_
| . | |  _|  _| . | . |
|_  |_|_| |_| |___|___|
|___| By @michenriksen

[*] Starting Gitrob version 1.1.2 at 2017-07-11 12:38 EDT
[*] Loading configuration... done
[*] Preparing database... failed
[!] Sequel::DatabaseConnectionError: PG::ConnectionBad: fe_sendauth: no password supplied

**Comment by arbazkiraak** [comment]
I have Created password for gitrob DB in postgres .

Now Problem is how to configure gitrob again ?

**Comment by blackappy** [comment]
A little guidance on how to reconfigure gitrob would be much appreciated.
gitrob --configure:

[*] Starting Gitrob version 1.1.2 at 2017-07-15 19:05 EDT
[*] Loading configuration... done
[*] Preparing database... failed
[!] Sequel::DatabaseConnectionError: PG::ConnectionBad: fe_sendauth: no password supplied

**Comment by arbazkiraak** [comment]
hi @blackappy  

cd $HOME

root@kali:~# ls -la | grep gitrob
-rw-r--r--  1 root root      135 Jul 11 12:42 .gitrobrc
root@kali:~# vi .gitrobrc 
---
sql_connection_uri: postgres://USERNAME:PASSWORD@localhost:5432/gitrob
github_access_tokens:
- GITUB ACCESS TOKEN Here.


Hope this will Fix !

**Comment by arbazkiraak** [comment]
hi @blackappy  

cd $HOME

root@kali:~#  ls -la | grep gitrob
-rw-r--r--  1 root root      135 Jul 11 12:42 .gitrobrc


root@kali:~# vi .gitrobrc 

 ```
sql_connection_uri: postgres://USERNAME:PASSWORD@localhost:5432/gitrob
 github_access_tokens:
- GITUB ACCESS TOKEN Here.

```

Just add your postgres username:password here 

Hope this will Fix !

**Comment by RatnamRaju** [comment]
Same error 

redis_1  | 24:M 20 Jul 03:25:41.504 * DB loaded from disk: 0.012 seconds
redis_1  | 24:M 20 Jul 03:25:41.504 * The server is now ready to accept connections on port 6379
app_1    | => Executing Rake db:migrate ...
app_1    |   ERROR -  Sequel::DatabaseConnectionError - PG::ConnectionBad: could not connect to server: Connection refused
app_1    | 	Is the server running on host "localhost" (::1) and accepting
app_1    | 	TCP/IP connections on port 5432?
app_1    | could not connect to server: Connection refused
app_1    | 	Is the server running on host "localhost" (127.0.0.1) and accepting
app_1    | 	TCP/IP connections on port 5432?
app_1    | :
app_1    |  /app/volumes/bundler/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:241:in `initialize'
app_1    | /app/volumes/bundler/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:241:in `initialize': PG::ConnectionBad: could not connect to server: Connection refused (Sequel::DatabaseConnectionError)
app_1    | 	Is the server running on host "localhost" (::1) and accepting
app_1    | 	TCP/IP connections on port 5432?
app_1    | could not connect to server: Connection refused
app_1    | 	Is the server running on host "localhost" (127.0.0.1) and accepting
app_1    | 	TCP/IP connections on port 5432?

**Comment by NaNdaWteK** [comment]
I have a similar problem to, if I run the migrations with a postgres connection it works.
But when I start the app with rake, sequel use the 127.168.1.1 ip to connect with the database instead of 127.0.0.1 that works fine. I intent force the host but at this moment I cannot.
The trace is this

``rerun --background -- rackup --port 4567 -o 0.0.0.0

09:11:55 [rerun] Libreria launched
09:11:55 [rerun] Rerun (10735) running Libreria (10739)
Traceback (most recent call last):
	46: from /usr/local/bin/rackup:23:in `<main>'
	45: from /usr/local/bin/rackup:23:in `load'
	44: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
	43: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
	42: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:283:in `start'
	41: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	40: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	39: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	38: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	37: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	36: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	35: from /var/www/libreria/config.ru:in `<main>'
	34: from /var/www/libreria/config.ru:in `new'
	33: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	32: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	31: from /var/www/libreria/config.ru:1:in `block in <main>'
	30: from /var/www/libreria/config.ru:1:in `require_relative'
	29: from /var/www/libreria/app.rb:2:in `<top (required)>'
	28: from /var/www/libreria/app.rb:2:in `require_relative'
	27: from /var/www/libreria/system/routes/valoration.rb:4:in `<top (required)>'
	26: from /var/www/libreria/system/routes/valoration.rb:4:in `require_relative'
	25: from /var/www/libreria/system/actions/book_valorations.rb:3:in `<top (required)>'
	24: from /var/www/libreria/system/actions/book_valorations.rb:3:in `require_relative'
	23: from /var/www/libreria/system/valoration/service.rb:1:in `<top (required)>'
	22: from /var/www/libreria/system/valoration/service.rb:1:in `require_relative'
	21: from /var/www/libreria/system/sequel/valorations_repository.rb:4:in `<top (required)>'
	20: from /var/www/libreria/system/sequel/valorations_repository.rb:4:in `require_relative'
	19: from /var/www/libreria/system/sequel/connection.rb:14:in `<top (required)>'
	18: from /usr/local/lib/ruby/2.6.0/singleton.rb:139:in `instance'
	17: from /usr/local/lib/ruby/2.6.0/singleton.rb:139:in `synchronize'
	16: from /usr/local/lib/ruby/2.6.0/singleton.rb:141:in `block in instance'
	15: from /usr/local/lib/ruby/2.6.0/singleton.rb:141:in `new'
	14: from /var/www/libreria/system/sequel/connection.rb:7:in `initialize'
	13: from /var/www/libreria/system/helpers/utils.rb:14:in `postgres_connection'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/core.rb:406:in `block (2 levels) in def_adapter_method'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/core.rb:399:in `adapter_method'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/core.rb:121:in `connect'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:58:in `connect'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:279:in `test_connection'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool.rb:127:in `make_new'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `connect'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `new'
/usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `initialize': could not connect to server: Connection refused (PG::ConnectionBad)
	Is the server running on host "192.168.1.1" and accepting
	TCP/IP connections on port 5432?
	46: from /usr/local/bin/rackup:23:in `<main>'
	45: from /usr/local/bin/rackup:23:in `load'
	44: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/bin/rackup:4:in `<top (required)>'
	43: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:148:in `start'
	42: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:283:in `start'
	41: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:354:in `wrapped_app'
	40: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:219:in `app'
	39: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/server.rb:319:in `build_app_and_options_from_config'
	38: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
	37: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
	36: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
	35: from /var/www/libreria/config.ru:in `<main>'
	34: from /var/www/libreria/config.ru:in `new'
	33: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
	32: from /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
	31: from /var/www/libreria/config.ru:1:in `block in <main>'
	30: from /var/www/libreria/config.ru:1:in `require_relative'
	29: from /var/www/libreria/app.rb:2:in `<top (required)>'
	28: from /var/www/libreria/app.rb:2:in `require_relative'
	27: from /var/www/libreria/system/routes/valoration.rb:4:in `<top (required)>'
	26: from /var/www/libreria/system/routes/valoration.rb:4:in `require_relative'
	25: from /var/www/libreria/system/actions/book_valorations.rb:3:in `<top (required)>'
	24: from /var/www/libreria/system/actions/book_valorations.rb:3:in `require_relative'
	23: from /var/www/libreria/system/valoration/service.rb:1:in `<top (required)>'
	22: from /var/www/libreria/system/valoration/service.rb:1:in `require_relative'
	21: from /var/www/libreria/system/sequel/valorations_repository.rb:4:in `<top (required)>'
	20: from /var/www/libreria/system/sequel/valorations_repository.rb:4:in `require_relative'
	19: from /var/www/libreria/system/sequel/connection.rb:14:in `<top (required)>'
	18: from /usr/local/lib/ruby/2.6.0/singleton.rb:139:in `instance'
	17: from /usr/local/lib/ruby/2.6.0/singleton.rb:139:in `synchronize'
	16: from /usr/local/lib/ruby/2.6.0/singleton.rb:141:in `block in instance'
	15: from /usr/local/lib/ruby/2.6.0/singleton.rb:141:in `new'
	14: from /var/www/libreria/system/sequel/connection.rb:7:in `initialize'
	13: from /var/www/libreria/system/helpers/utils.rb:14:in `postgres_connection'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/core.rb:406:in `block (2 levels) in def_adapter_method'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/core.rb:399:in `adapter_method'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/core.rb:121:in `connect'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:58:in `connect'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:279:in `test_connection'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
	 4: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
	 3: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/connection_pool.rb:127:in `make_new'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `connect'
	 1: from /usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `new'
/usr/local/lib/ruby/gems/2.6.0/gems/sequel-5.16.0/lib/sequel/adapters/postgres.rb:206:in `initialize': **PG::ConnectionBad: could not connect to server: Connection refused (Sequel::DatabaseConnectionError)
	Is the server running on host "192.168.1.1" and accepting
	TCP/IP connections on port 5432?**

09:11:57 [rerun] Libreria Launch Failed
09:11:57 [rerun] Watching . for **/*.{rb,js,coffee,css,scss,sass,erb,html,haml,ru,yml,slim,md,feature,c,h} with Linux adapter

**Comment by mihir9455** [comment]
> hi @blackappy
> 
> cd $HOME
> 
> root@kali:~# ls -la | grep gitrob
> -rw-r--r-- 1 root root 135 Jul 11 12:42 .gitrobrc
> 
> root@kali:~# vi .gitrobrc
> 
> ```
> sql_connection_uri: postgres://USERNAME:PASSWORD@localhost:5432/gitrob
> github_access_tokens:
> - GITUB ACCESS TOKEN Here.
> ```
> 
> Just add your postgres username:password here
> 
> Hope this will Fix !

how to save it after editing?

**Comment by jagadeeshdevula** [comment]
Hi, mihir9455,

Just press ESC after then :wq!

That's it.

**Comment by preethamarun00** [comment]
Check your internet: step 1
Step 2 : check that all software ra install by supporting to database and
connect to tomcat server and 8080
