### ISSUE TITLE
I can not run configure after install.

### ISSUE THREAD

**Issue by SmokyJp** [michenriksen/gitrob#104]
After install and run gitrob configure, I get this :

./gitrob configure
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- gitrob (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./gitrob:3:in `<main>'

uname -a
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.16-1kali1 (2017-03-24) x86_64 GNU/Linux

**Comment by michenriksen** [comment]
Did you install with `gem install gitrob` or did you clone the repo?
