### ISSUE TITLE
How to analyze flagged files without completing afull scan of an organization?

### ISSUE THREAD

**Issue by tomeddistone** [michenriksen/gitrob#106]
Sometimes when analyzing a big company gitrob stops scanning due to excessive scanning and I kill the process.
When I access the gitrob panel at 127.0.0.1:9393, I can't see and access those flagged files at all (company's assessment is not clickable).
**So the question is:** Is it possible to analyze files that have already been flagged after killing the process of analyzing? If yes, then how?
Your help would be highly appreciated

**Comment by michenriksen** [comment]
Hi there, that sounds odd. Does it completely die and error out or become unresponsive?

Unless the scan finishes, the assessment is flagged as "in progress". You can change the status flag directly in the database, but that is of course a pretty hacky solution. :/

**Comment by ivanramone** [comment]
@michenriksen it just becomes unresponsive
Could you tell me the easiest way to change the status flag directly?
