### ISSUE TITLE
Sequel Deprecation Warning

### ISSUE THREAD

**Issue by mustaqiimuhar** [michenriksen/gitrob#107]
Should I be concern with this warning? I'm not able to view the webpage as there's no response from it :\

[*] Preparing database...SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/model/base.rb:833:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:4:in `<class:Assessment>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:140:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/model/base.rb:833:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:4:in `<class:GithubAccessToken>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:141:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/model/base.rb:833:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:4:in `<class:Owner>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:142:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/model/base.rb:833:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:4:in `<class:Repository>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:143:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/model/base.rb:833:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:4:in `<class:Blob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:144:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/model/base.rb:833:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:4:in `<class:Flag>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:145:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.46.0/lib/sequel/model/base.rb:833:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:4:in `<class:Comparison>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:146:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
 done
[*] Starting web application on port 9393...
== Sinatra (v1.4.8) has taken the stage on 9393 for production with backup from Thin
Thin web server (v1.7.0 codename Dunder Mifflin)
Maximum connections set to 1024
Listening on 127.0.0.1:9393, CTRL+C to stop

**Comment by phackt** [comment]
Any comments on that?

**Comment by mustaqiimuhar** [comment]
@phackt nothing much, Gitrob still runs as per usual. Those are just warnings to indicate that `Sequel::Model.set_allowed_columns` is a deprecated function. To resolve the warning, its best to use `set_only` or [`set_fields`](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Model/ClassMethods.html#method-i-set_allowed_columns)

**Comment by HassanKhanYusufzai** [comment]
Hi guys getting this error what to do???

[*] Starting Gitrob version 1.1.2 at 2017-10-06 11:43 PKT
[*] Loading configuration... done
[*] Preparing database...SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:4:in `<class:Assessment>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/assessment.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:140:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:4:in `<class:GithubAccessToken>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/github_access_token.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:141:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:4:in `<class:Owner>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/owner.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:142:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:4:in `<class:Repository>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:143:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:4:in `<class:Blob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/blob.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:144:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:4:in `<class:Flag>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/flag.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:145:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.3.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:4:in `<class:Comparison>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:3:in `<module:Models>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/models/comparison.rb:1:in `<top (required)>'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:146:in `load_models'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
 done
Could not find command "svn".

**Comment by itachi73** [comment]
@Splint3r7  I have the same issue, have you found any solution ?
