### ISSUE TITLE
Can't access GitLab Personal Access Tokens

### ISSUE THREAD

**Issue by karanmilan** [michenriksen/gitrob#108]
When I try to configure GitRob by using the command gitrob --configure 
I can enter all the details but when I enter the Personal Access Token when prompted it doesn't recognize it I guess because when I enter one token and then the next line blank to stop the process, it just goes on and on. Asking me for GitHub Access tokens

**Comment by michenriksen** [comment]
Gitrob only works against github.com. I guess GitLab's access tokens follow a different format and Gitrob therefore sees them as invalid.
