### ISSUE TITLE
Content Analysis - finding sensitive information by analysing file contents

### ISSUE THREAD

**Issue by inspaya** [michenriksen/gitrob#109]
**How this works**                       
Using a combination of regular expressions and mathematical calculations, file contents are analyzed for potentially sensitive credentials. This approach does not rely on the extension alone. By default all file extensions are scanned except the user excludes some in a configuration file.
 
**Current and suggested behavior**
The current behavior is that Gitrob relies on the file extensions of files in a repo to perform analysis. This leads to sensitive information contained in other files being missed/ignored e.g. private keys in `.php` files for example. The suggested behavior is to rely on the actual contents of a file rather than its extension for analysis

**Why would the enhancement be useful to most users**
This enhancement increases the accuracy of identifying sensitive information with Gitrob

**Screenshots and GIFs**
None yet

**Gitrob Version:** `1.1.2`                                                          
**OS and Version:** Tested on `Mac OS 10` and `Ubuntu 16`

**Extra**
Appears related to #93

**Comment by inspaya** [comment]
@michenriksen please review and provide feedback. Thanks

**Comment by poon64** [comment]
When I am checking the result of the scan I can see that there are files missing that I know include usernames and passwords. It seems like the scan only relies to the name of the files. 
I am using the version 1.1.2 of GitRob. 
Do I have to do anything specific to make it scan the contents of the files after the word "password"? 
I am scanning on GitHub Enterprise organizations. 

/Peter

**Comment by Essenpreis** [comment]
I've modified Gitrob to scan for file contents! Gitrob does not support this out of the box. 

Just look into my forks. It works pretty well including number of regular expressions to search for all kinds of secrets.

If someone helps me with some code beautifications I'd file a pull request.

**Comment by inspaya** [comment]
@Essenpreis thanks for looking into it.

**Comment by e1337** [comment]
Hi, Any updates on this?
