### ISSUE TITLE
Redo gitrob configure

### ISSUE THREAD

**Issue by bhheneghan** [michenriksen/gitrob#114]
I running Kali and I screwed up gitrob configure and now I cannot run it.  My error is below.  I also cannot find ~/.gitrobrc.

How can rerun the configure?

[*] Starting Gitrob version 1.1.2 at 2017-07-28 11:01 EDT
[*] Loading configuration... done
[*] Preparing database... failed
[!] URI::InvalidURIError: bad URI(is not URI?): postgres://gitrob:xxxx@xxxx@gitrob:5432/gitrob

**Comment by danyalzafar420** [comment]
I also have the same issue :(

**Comment by poon64** [comment]
Check the ~/.gitrobrc 
It seems like you have the @ in your password, that could cause a problem. 
The URI in .gitrobrc should look something like this, 
sql_connection_uri: postgres://gitrob:PASSWORD@localhost:5432/gitrob

**Comment by danyalzafar420** [comment]
Please guide how to check ~/.gitrobrc because i could not find its path.. :(

**Comment by poon64** [comment]
That is the path :) 
The .gitrobrc is located in your home directory, so ~/.gitrobrc will take you there, if you do "ls -al ~/.gitrobrc" (without the "") you should be able to see the file, and if you replace the ls with cat you will se the content of the file.

**Comment by danyalzafar420** [comment]
![per](https://user-images.githubusercontent.com/10330087/30237469-863c71a2-94e7-11e7-820e-bc63605fa69f.PNG)

Tried and here are results

**Comment by poon64** [comment]
When doing the cat command you shouldn't have the -al, that was for the ls command, forgot to remove that, sorry. 
So if you do, "cat /root/.gitrobrc" (without the "") you should see the content of the .gitrobrc

**Comment by danyalzafar420** [comment]
Dear @poon64 
Thanks a lot for the help.. I have this issue to resolve now how to resolve it.. whether i have to remove all the text from /root/.gitrob ? or perhaps remove the downloaded gitrob and again downloading all stuff and configuring ?
![git](https://user-images.githubusercontent.com/10330087/30239423-10ac6c9c-9511-11e7-9574-ccc24477c7a6.PNG)

**Comment by poon64** [comment]
Try to delete the .gitrobrc file with "rm /root/.gitrobrc" and then recreate the file again with command "gitrob configure"

**Comment by attacker420** [comment]
![ser2](https://user-images.githubusercontent.com/10330087/31183551-c512dea4-a8db-11e7-9aa0-71ddfa81df7a.PNG)
Dear @poon64  

Thanks I tried and attaching results..
![ser](https://user-images.githubusercontent.com/10330087/31183516-a953fc2a-a8db-11e7-9560-ce629818a060.PNG)

**Comment by attacker420** [comment]
![ser2](https://user-images.githubusercontent.com/10330087/31183822-8e00afc6-a8dc-11e7-823c-f831d5e8f6cd.PNG)
Dear @poon64 ,
Thanks , I have tried but again failed with same Error.. This time i have not included any special chars in my password.
Kindly look at the attached images.
![ser](https://user-images.githubusercontent.com/10330087/31183808-8331e3a8-a8dc-11e7-9cdf-053420b20235.PNG)
