### ISSUE TITLE
Kali 4.13 and below ERROR: Failed to build gem native extension: nokogiri

### ISSUE THREAD

**Issue by 0xtavian** [michenriksen/gitrob#119]
You must first install these dependencies for nokogiri before a successful install.
Source is the official documentation:
http://www.nokogiri.org/tutorials/installing_nokogiri.html 
 
To fix:
###  root@kali:~# sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev

 **Terminal output unsuccessful to successful **

### root@kali:~# gem install gitrob
Fetching: colorize-0.8.1.gem (100%)
Successfully installed colorize-0.8.1
Fetching: highline-1.7.10.gem (100%)
Successfully installed highline-1.7.10
Fetching: thread-0.2.2.gem (100%)
Successfully installed thread-0.2.2
Fetching: ruby-progressbar-1.9.0.gem (100%)
Successfully installed ruby-progressbar-1.9.0
Fetching: pg-0.21.0.gem (100%)
Building native extensions. This could take a while...
Successfully installed pg-0.21.0
Fetching: sequel-4.49.0.gem (100%)
Successfully installed sequel-4.49.0
Fetching: hashie-3.5.6.gem (100%)
Successfully installed hashie-3.5.6
Fetching: jwt-1.5.6.gem (100%)
Successfully installed jwt-1.5.6
Fetching: multi_xml-0.6.0.gem (100%)
Successfully installed multi_xml-0.6.0
Fetching: oauth2-1.4.0.gem (100%)
Successfully installed oauth2-1.4.0
Fetching: mini_portile2-2.1.0.gem (100%)
Successfully installed mini_portile2-2.1.0
Fetching: nokogiri-1.6.8.1.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing gitrob:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.6.8.1/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20171211-8943-13yk714.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.1.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.8.1/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.6.8.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.8.1/gem_make.out

## # root@kali:~# sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.4).
build-essential set to manually installed.
patch is already the newest version (2.7.5-1+b2).
patch set to manually installed.
ruby-dev is already the newest version (1:2.3.3).
ruby-dev set to manually installed.
Suggested packages:
  liblzma-doc
The following NEW packages will be installed:
  liblzma-dev zlib1g-dev
0 upgraded, 2 newly installed, 0 to remove and 602 not upgraded.
Need to get 497 kB of archives.
After this operation, 1,093 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://archive-7.kali.org/kali kali-rolling/main amd64 liblzma-dev amd64 5.2.2-1.3 [292 kB]
Get:2 http://archive-7.kali.org/kali kali-rolling/main amd64 zlib1g-dev amd64 1:1.2.8.dfsg-5 [205 kB]
Fetched 497 kB in 1s (458 kB/s) 
Selecting previously unselected package liblzma-dev:amd64.
(Reading database ... 319426 files and directories currently installed.)
Preparing to unpack .../liblzma-dev_5.2.2-1.3_amd64.deb ...
Unpacking liblzma-dev:amd64 (5.2.2-1.3) ...
Selecting previously unselected package zlib1g-dev:amd64.
Preparing to unpack .../zlib1g-dev_1%3a1.2.8.dfsg-5_amd64.deb ...
Unpacking zlib1g-dev:amd64 (1:1.2.8.dfsg-5) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up liblzma-dev:amd64 (5.2.2-1.3) ...
Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-5) ...

### # root@kali:~# gem install gitrob
Building native extensions. This could take a while...
Successfully installed nokogiri-1.6.8.1
Fetching: descendants_tracker-0.0.4.gem (100%)
Successfully installed descendants_tracker-0.0.4
Fetching: github_api-0.13.0.gem (100%)
Successfully installed github_api-0.13.0
Fetching: concurrent-ruby-1.0.5.gem (100%)
Successfully installed concurrent-ruby-1.0.5
Fetching: sucker_punch-2.0.4.gem (100%)
Sucker Punch v2.0 introduces backwards-incompatible changes.
Please see https://github.com/brandonhilkert/sucker_punch/blob/master/CHANGES.md#200 for details.
Successfully installed sucker_punch-2.0.4
Fetching: gitrob-1.1.2.gem (100%)
Successfully installed gitrob-1.1.2
Parsing documentation for nokogiri-1.6.8.1
Installing ri documentation for nokogiri-1.6.8.1
Parsing documentation for descendants_tracker-0.0.4
Installing ri documentation for descendants_tracker-0.0.4
Parsing documentation for github_api-0.13.0
Installing ri documentation for github_api-0.13.0
Parsing documentation for concurrent-ruby-1.0.5
Installing ri documentation for concurrent-ruby-1.0.5
Parsing documentation for sucker_punch-2.0.4
Installing ri documentation for sucker_punch-2.0.4
Parsing documentation for gitrob-1.1.2
Installing ri documentation for gitrob-1.1.2
Done installing documentation for nokogiri, descendants_tracker, github_api, concurrent-ruby, sucker_punch, gitrob after 10 seconds
6 gems installed
root@kali:~#

**Comment by securityaspirations** [comment]
This fixed it for me as well, thanks very much

**Comment by omsai5467** [comment]
Bro can u make how to bind APK
