### ISSUE TITLE
Option for targeting repositories instead of organizations

### ISSUE THREAD

**Issue by maboe** [michenriksen/gitrob#12]
Could you please add an option for targeting repositories instead of organizations? Sometimes organizations simply don't have an official github account but it might be possible to find other repositories that are related to the organization, for example through google. 
Otherwise it's a really nice tool.

Would really love to see this added.

**Comment by karlnp** [comment]
I would also love to see this.

**Comment by michenriksen** [comment]
Hi @maboe and @karlnp, I am planning to add an option where it will be possible to give Gitrob a comma-separated list of users to scan, would that be satisfactory? 

I also need to think about how this would be presented in the web interface, when users don't belong to an organization. If you have any ideas, please let me know.

**Comment by karlnp** [comment]
This would definitely work. As I don't have an organization to test with, I have only the screenshots to work against, but perhaps there could be a top-level fork between "Organizations" and "Unaffiliated Users"?

**Comment by michenriksen** [comment]
@karlnp thanks for the input. I think the way to go will be to introduce a new model to represent a check or and assessment, or what it's going to be called, which can reference an organization or a collection or arbitrary users.

For now, if you need to check a collection of users, you can always create a placeholder organization and join them under there. I think as an owner of the org, you can also set the memberships as non-public if you don't want to disclose that information.

**Comment by maboe** [comment]
@michenriksen Thanks a lot for addressing this. A comma separated list sounds great. For larger lists of users it might be useful to include them as a file.
I'm not really sure about the presentation within the web interface, as I also haven't been able to test it against an organization.

**Comment by ghyde** [comment]
I'm not in an organization, but I would like to check all of my repositories (a `-u USERNAME` option). Or if I only wanted to check a specific repository, a `-r NAME/REPO` option would be awesome as well.

**Comment by biddster** [comment]
+1 for this too.

**Comment by michenriksen** [comment]
The new version of Gitrob now supports scanning of one or more users. [Read more here](http://michenriksen.com/blog/new-version-of-gitrob-is-out/).

**Comment by dawphy** [comment]
> Hi @maboe and @karlnp, I am planning to add an option where it will be possible to give Gitrob a comma-separated list of users to scan, would that be satisfactory?
> 
> I also need to think about how this would be presented in the web interface, when users don't belong to an organization. If you have any ideas, please let me know.



> Hi @maboe and @karlnp, I am planning to add an option where it will be possible to give Gitrob a comma-separated list of users to scan, would that be satisfactory?
> 
> I also need to think about how this would be presented in the web interface, when users don't belong to an organization. If you have any ideas, please let me know.

Hi Mike, I was checking the current gitrob and it has an option to pass multiple users and organizations. Thanks for the update. I also have a couple of questions. 1) Can we target and scan specific repository under a user like "gitrob  target url https://github.com/dawphy/TechTech"  ? . Under user dawphy, there might be multiple repositories and but if we want to scan specific ones.  2) Does the current gitrob supports notification functionality to users that undergo a scan? Thanks :)
