### ISSUE TITLE
[request] Check file contents as well as file extensions

### ISSUE THREAD

**Issue by northdpole** [michenriksen/gitrob#121]
Hi, I was wondering if it's on the roadmap to add rules to check for secrets in source code. So far the "part" in the rules only accepts filename, path and extension.

If it isn't, would you be open to a pull request which would add this functionality? 

Thanks

**Comment by Essenpreis** [comment]
I've modified Gitrob to scan for file contents! Just look into my forks. It works pretty well including number of regular expressions to search for all kinds of secrets. 

If someone helps me with some code beautifications I'd file a pull request.
