### ISSUE TITLE
gitrob configure. Nothing happens afterwards.

### ISSUE THREAD

**Issue by dracohacker** [michenriksen/gitrob#123]
root@dragon:/home/master# gitrob
[*] Starting Gitrob version 1.1.2 at 2018-02-20 16:02 UTC
[*] Starting Gitrob configuration wizard
Enter PostgreSQL hostname: |localhost|
Enter PostgreSQL port: |5432|
Enter PostgreSQL username: |gitrob|
Enter PostgreSQL password (masked): xxxxxx
Enter PostgreSQL database name: |gitrob|
Enter GitHub access tokens (blank line to stop):
c2f386a[REMOVED SOME PART]5df2b
^C/var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:869:in `eof?': Interrupt
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:869:in `get_line'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:891:in `get_response'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:264:in `ask'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:785:in `gather'
        from /var/lib/gems/2.3.0/gems/highline-1.7.10/lib/highline.rb:254:in `ask'
        from /usr/lib/ruby/2.3.0/forwardable.rb:204:in `ask'
        from /var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli/commands/configure.rb:90:in `gather_access_tokens'
        from /var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli/commands/configure.rb:52:in `gather_configuration'
        from /var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli/commands/configure.rb:16:in `initialize'
        from /var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli/command.rb:7:in `new'
        from /var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli/command.rb:7:in `start'
        from /var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:96:in `configure'
        from /var/lib/gems/2.3.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:52:in `initialize'
        from /usr/lib/ruby/vendor_ruby/thor.rb:365:in `new'
        from /usr/lib/ruby/vendor_ruby/thor.rb:365:in `dispatch'
        from /usr/lib/ruby/vendor_ruby/thor/base.rb:444:in `start'
        from /var/lib/gems/2.3.0/gems/gitrob-1.1.2/exe/gitrob:5:in `<top (required)>'
        from /usr/local/bin/gitrob:23:in `load'
        from /usr/local/bin/gitrob:23:in `<main>'

root@dragon:/home/master# gitrob
[*] Starting Gitrob version 1.1.2 at 2018-02-20 16:10 UTC
[*] Starting Gitrob configuration wizard
Enter PostgreSQL hostname: |localhost|
Enter PostgreSQL port: |5432|
Enter PostgreSQL username: |gitrob|
Enter PostgreSQL password (masked): xxxxxx
Enter PostgreSQL database name: |gitrob|
Enter GitHub access tokens (blank line to stop):
c2f386a[REMOVED SOME PART]5df2b

Nothing happens once I enter GitHub access token. Waited for more than 40 minutes, nothing happened. When I hit Ctrl+c, top most error is what I receive.

**Comment by udaygoudkandyanam** [comment]
What's the resolution here? can you please let us know
