### ISSUE TITLE
SEQUEL DEPRECATION WARNING:

### ISSUE THREAD

**Issue by Vjay615** [michenriksen/gitrob#125]
I am getting this error when i run gitrob -o GitHub
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.
/var/lib/gems/2.5.0/gems/sequel-4.49.0/lib/sequel/model/base.rb:848:in `set_allowed_columns'
/var/lib/gems/2.5.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:4:in `<class:Repository>'
/var/lib/gems/2.5.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:3:in `<module:Models>'
/var/lib/gems/2.5.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:2:in `<module:Gitrob>'
/var/lib/gems/2.5.0/gems/gitrob-1.1.2/lib/gitrob/models/repository.rb:1:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/var/lib/gems/2.5.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:143:in `load_models'
/var/lib/gems/2.5.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:135:in `block in prepare_database'
/var/lib/gems/2.5.0/gems/gitrob-1.1.2/lib/gitrob/cli.rb:156:in `task'
SEQUEL DEPRECATION WARNING: Sequel::Model.set_allowed_columns is deprecated and will be removed in Sequel 5.  Load the whitelist_security plugin into the model class.

Any seen this and have a fix ?

**Comment by susheel264** [comment]
Me to having the same issue.

**Comment by jagadeeshdevula** [comment]
Better to you both can follow this command.
Ex:-  gitrob analyze GitHub
