### ISSUE TITLE
Feature Request: Gitrob to scan file contents as well 

### ISSUE THREAD

**Issue by Essenpreis** [michenriksen/gitrob#134]
Hi,
Great work on the Go-version. I once forked the former Ruby version and implemented a version so that Gitrob can scan file contents as well. This small adaption went along with a signatures.json having sort of sophisticated regular expressions in order to be able to search e.g. for keys/passwords inside files.

https://github.com/Essenpreis/gitrob/blob/master/signatures.json
and here's my fork: https://github.com/Essenpreis/gitrob

It would be great if the new Gitrob also would be able to scan inside files as well.

Mathias

**Comment by mriduam** [comment]
Hi Mathias,

Currently I am also running older ruby version of Gitrob and wants to scan my file content for hard coded user credentials. I have tried to inject all your content rules into my signature.json file but It is still not detecting any credentials in file for me.

Any suggestions on how it worked for you or what I am missing out? I will appreciate your help on this.
Thanks
Mishra

**Comment by michenriksen** [comment]
Thanks for the feedback! I see this as out of scope for the time being.
