### ISSUE TITLE
Question on "Viewing a finding, Interesting things are highlighted" 

### ISSUE THREAD

**Issue by mriduam** [michenriksen/gitrob#135]
Hey there and thank you for using the issue tracker!

## Checklist before filing an issue:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com), [StackExchange Security](https://security.stackexchange.com) or similar platform.
- [ ] Have an idea for a feature? Make sure that it hasn't been suggested before and describe your idea in detail.

## None of the above? create a bug report

Make sure to add **all the information needed to understand the bug** so that someone can help. If information is missing, the issue will be labeled with 'Needs more information' and closed until there is enough information.

## Expected Behavior
Highlight user credentials inside a flagged file.

## Actual Behavior
Just highlights **abcxyz.com** "Viewing a finding. Interesting things are highlighted"

## Steps to Reproduce the Problem

  1. Go to a flagged :finding file
  2. see the highlighted content
  3.

## Specifications

  - Gitrob version: 1.1.2
  - Operating system: Kali linux
  - Go version:
****

**Comment by mriduam** [comment]
![screen shot 2018-06-11 at 3 22 38 pm](https://user-images.githubusercontent.com/39810263/41377093-e1ac40b4-6f0f-11e8-98f6-52421366ab35.png)

**Comment by michenriksen** [comment]
This is the old ruby version of Gitrob which I no longer support. Check out the latest version!

**Comment by mriduam** [comment]
Hi, 
So, does the new Go version supports file content inspection for secrets and passwords?
Thanks
Mishra
