### ISSUE TITLE
Does new version of Gitrob supports TLS when binding the server to new IP? 

### ISSUE THREAD

**Issue by mriduam** [michenriksen/gitrob#136]
Hey there and thank you for using the issue tracker!

## Checklist before filing an issue:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com), [StackExchange Security](https://security.stackexchange.com) or similar platform.
- [ ] Have an idea for a feature? Make sure that it hasn't been suggested before and describe your idea in detail.

## None of the above? create a bug report

Make sure to add **all the information needed to understand the bug** so that someone can help. If information is missing, the issue will be labeled with 'Needs more information' and closed until there is enough information.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Gitrob version:
  - Operating system:
  - Go version:

**Comment by michenriksen** [comment]
TLS is not supported. You would need to put something like nginx in front of it if you want TLS.
