### ISSUE TITLE
prettify.js not working when not root

### ISSUE THREAD

**Issue by nielsole** [michenriksen/gitrob#14]
`Unexpected error while processing request: Permission denied - /var/lib/gems/1.9.1/gems/gitrob-0.0.3/public/javascripts/prettify.js`
And it really is only available to root: `-rw-r-----`

Therefore prettify only works when running gitrob with sudo. 
Great tool btw!
I am using Ubuntu 14.04.1 LTS.

**Comment by michenriksen** [comment]
Hi @nielsole, thanks for reporting. I've changed the permissions on the prettify files to have read access for all. Hopefully that will be reflected next time I push a new version of the gem.

**Comment by michenriksen** [comment]
I've pushed a new version of Gitrob, which should have fixed this issue. Could you do a `gem update gitrob` and verify that it's fixed?

**Comment by nielsole** [comment]
Wow thanks for the fast reply and fix. I will have it checked by Monday.

On Sat, Jan 17, 2015 at 3:50 PM, Michael Henriksen <notifications@github.com

**Comment by nielsole** [comment]
Can confirm that after updating, Prettify.js works without root.
After updating I was prompted to accept the license/disclaimer. This seems to also only work when being root :) 

    Errno::EACCES: Permission denied - /var/lib/gems/1.9.1/gems/gitrob-0.0.4/lib/../agreement

**Comment by michenriksen** [comment]
Hmm... making the gem folder world writable sounds a little risky to me, I guess you install Gitrob with `sudo gem install gitrob` and then run Gitrob afterwards without sudo, correct?

**Comment by nielsole** [comment]
That is correct. But I need to run it as sudo first to accept the license (so yeah). Maybe touch the agreement file on install and make it writable so that you do not need to make the entire folder writable.

**Comment by michenriksen** [comment]
yeah, I'll look into having the file already present. I'll close this issue since it was about prettify.js not working. 

Thanks!
