### ISSUE TITLE
Blog and documentation site michenriksen.com no longer has a domain?

### ISSUE THREAD

**Issue by jdickey** [michenriksen/gitrob#160]
Browsing http://www.michenriksen.com/ yields a 404, and `nslookup michenriksen.com` reports an `NXDOMAIN` (no such domain) error. Are the docs available elsewhere?

**Comment by muffix** [comment]
I think there has never been much more than the [README](https://github.com/michenriksen/gitrob/blob/master/README.md) file.

**Comment by michenriksen** [comment]
I forgot to renew my domain, but was luckily reserved by Gandi 😆
