### ISSUE TITLE
User Interface not working in Windows 10

### ISSUE THREAD

**Issue by payloadartist** [michenriksen/gitrob#161]
Solved...

**Comment by dzhenway** [comment]
me too
after clicking gitrob.exe
just pop up for a while then nothing happened

**Comment by mattyjones** [comment]
@dzhenway @payloadartist I am migrating this to the new [fork](https://github.com/mattyjones/gitrob) as this project is no longer maintained. mattyjones/gitrob#16 Please update that bug with any additional info.

**Comment by payloadartist** [comment]
I think building from source is a better option. Able to get the server up & running, and access the UI, after building from source.
