### ISSUE TITLE
Github API pagination not supported

### ISSUE THREAD

**Issue by jmuellerAS24** [michenriksen/gitrob#18]
I wasn't able to see my organization's private repositories. The hints in #17 didn't help me.
But I found out that gitrob doesn't seem to support pagination of the Github API.
All the private repositories show up on page 2 only which is why I could not see them.
So please add pagination support.

**Comment by michenriksen** [comment]
Oh man, what a stupid bug. I've fixed it in the latest version (0.0.5) - Just do `gem update gitrob` to get it.

Thanks for reporting the issue!
