### ISSUE TITLE
error on building: src/github.com/gin-gonic/gin/context.go:80:11: undefined: http.SameSite

### ISSUE THREAD

**Issue by spekulatius** [michenriksen/gitrob#197]
Hey there and thank you for using the issue tracker!

## Checklist before filing an issue:

- [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [ ] Have a usage question? Ask your question on [StackOverflow](http://stackoverflow.com), [StackExchange Security](https://security.stackexchange.com) or similar platform.
- [ ] Have an idea for a feature? Make sure that it hasn't been suggested before and describe your idea in detail.

## None of the above? create a bug report

Make sure to add **all the information needed to understand the bug** so that someone can help. If information is missing, the issue will be labeled with 'Needs more information' and closed until there is enough information.

## Expected Behavior

./build.sh to successfully build a package

## Actual Behavior

Fails with this error message:

![image](https://user-images.githubusercontent.com/8433587/82139115-bd4fc900-9836-11ea-92d5-1d5060d3130f.png)

## Steps to Reproduce the Problem

  1. git clone https://github.com/michenriksen/gitrob
  2. ./build.sh

## Specifications

  - Gitrob version: dev-master
  - Operating system: elementary os
  - Go version: go version go1.10.4 linux/amd64

**Comment by HollywoodMarks** [comment]
SameSite requires Go 1.11
This is because it sets the SameSite attribute on the session cookie for additional security, but that attribute is only supported in 1.11 onwards.
https://github.com/alexedwards/scs/issues/60

**Comment by spekulatius** [comment]
Ah, thanks for pointing me in the right direction @HollywoodMarks. Now I'm running into the next error:

```
[...].go/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal
```

**Comment by mattyjones** [comment]
@spekulatius I am not sure where that is coming from. Are you getting that error on building or on running it? I am not seeing that issue in the latest build of my [fork](https://github.com/mattyjones/gitrob). You can try building that using the script. I am building and running on OSX. I can test on a Windows10 or Linux box if needed.

**Comment by sabeesh03** [comment]
MACBOOK1:gitrob INDIRA$ ./build.sh
[*] Building linux/amd64 ...
# github.com/michenriksen/gitrob/core
../../../../../../Desktop/GO/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal
[*] Building darwin/amd64 ...
# github.com/michenriksen/gitrob/core
../../../../../../Desktop/GO/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal
[*] Building windows/amd64 ...
# github.com/michenriksen/gitrob/core
../../../../../../Desktop/GO/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal
shasum: *:


  0B	checksums.txt
MACBOOK1:gitrob INDIRA$ getting that error on building AND running it

**Comment by sabeesh03** [comment]
go get github.com/michenriksen/gitrob
# github.com/michenriksen/gitrob/core
../Desktop/GO/src/github.com/michenriksen/gitrob/core/router.go:41:54: too few values in assetfs.AssetFS literal

**Comment by mattyjones** [comment]
@sabeesh03 Can you please pull from the updated [repo](https://github.com/mattyjones/gitrob) and confirm the issue still exists. I cannot replicate this and the code in this repo has diverged quite a bit from my fork at this point as this repo is not maintained. As I explained in #198 I am going to assume maintainership of this project in the above repo and continue to develop it.

**Comment by spekulatius** [comment]
Hey @mattyjones 

thanks for picking the project up and continuing it! I've just pulled your repo and run `./build.sh`. It failed with these messages:

![image](https://user-images.githubusercontent.com/8433587/82643484-a0453c80-9c20-11ea-89a3-6796ea26dc98.png)

Peter

**Comment by mattyjones** [comment]
@spekulatius yea...type assertion goodness. I will look into it and poke here if/when I can nail it down.

**Comment by mattyjones** [comment]
@spekulatius This should be fixed now, I missed a step in the brain transplant where it was looking for the original project and not the new fork. One of the pr's fixed another bug in the type assertion that was not fixed in the original project. The code still and always will reflect the original project but all previous libraries, pointer, packages, etc are now the latest versions and only pulling from my repo to avoid this in the future.

**Comment by spekulatius** [comment]
Yay, awesome. I've pull it and it run through without any issues. Thank you @mattyjones! 

I'll close this to clean up the issues.
