### ISSUE TITLE
running gitrob with no options presents the somewhat cryptic message "Cannot find Github organization with that name"

### ISSUE THREAD

**Issue by kevinburke** [michenriksen/gitrob#2]
```
/opt/rubies/2.1.2/bin/gitrob
      _ _           _
  ___|_| |_ ___ ___| |_
 | . | |  _|  _| . | . |
 |_  |_|_| |_| |___|___|
 |___| By @michenriksen

 [*] Starting Gitrob version 0.0.2 at 2015-01-13 03:12 PST
 [*] Loading configuration... done
 [*] Preparing SQL database... done
 [*] Loading file patterns... done
 [!] Cannot find GitHub organization with that name; exiting.
```

**Comment by christianbundy** [comment]
I'm assuming it's looking for `​` (empty string).

**Comment by michenriksen** [comment]
Yes, that is probably what is happening. I'll get that fixed up. Thanks for reporting!

**Comment by phantasm-sd** [comment]
I'm seeing the same thing from 0.0.3 as well:
      _ _           _
  ___|_| |_ ___ ___| |_
 | . | |  _|  _| . | . |
 |_  |_|_| |_| |___|___|
 |___| By @michenriksen

 [*] Starting Gitrob version 0.0.3 at 2015-01-15 12:16 PST
 [*] Loading configuration... done
 [*] Preparing SQL database... done
 [*] Loading file patterns... done
 [!] Cannot find GitHub organization with that name; exiting.

**Comment by michenriksen** [comment]
Fixed in the newest version.
