### ISSUE TITLE
Consider changing db cleanup stdout text to something less heart-attacky

### ISSUE THREAD

**Issue by eefahy** [michenriksen/gitrob#22]
Not to be too picky but it gave me a bit of a jolt. Perhaps:
` [*] Deleting existing <orgname> organization from database...`

**Comment by michenriksen** [comment]
Haha! I see what you mean. I'm actually thinking about removing the automatic deletion of old organization checks completely, as it is really slow at the moment if the org is big.

**Comment by eefahy** [comment]
:+1: Sounds good, thanks.
