### ISSUE TITLE
Change bcrypt-ruby dependency to use bcrypt

### ISSUE THREAD

**Issue by rajeshkp** [michenriksen/gitrob#23]
Change bcrypt-ruby dependency to use bcrypt

>>
gem install gitrob
Fetching: methadone-1.8.0.gem (100%)
Successfully installed methadone-1.8.0
Fetching: paint-0.9.0.gem (100%)
Successfully installed paint-0.9.0
Fetching: thread-0.1.4.gem (100%)
Successfully installed thread-0.1.4
Fetching: addressable-2.3.6.gem (100%)
Successfully installed addressable-2.3.6
Fetching: dm-core-1.2.1.gem (100%)
Successfully installed dm-core-1.2.1
Fetching: dm-aggregates-1.2.0.gem (100%)
Successfully installed dm-aggregates-1.2.0
Fetching: dm-constraints-1.2.0.gem (100%)
Successfully installed dm-constraints-1.2.0
Fetching: dm-migrations-1.2.0.gem (100%)
Successfully installed dm-migrations-1.2.0
Fetching: dm-transactions-1.2.0.gem (100%)
Successfully installed dm-transactions-1.2.0
Fetching: json_pure-1.8.2.gem (100%)
Successfully installed json_pure-1.8.2
Fetching: dm-serializer-1.2.2.gem (100%)
Successfully installed dm-serializer-1.2.2
Fetching: dm-timestamps-1.2.0.gem (100%)
Successfully installed dm-timestamps-1.2.0
Fetching: dm-validations-1.2.0.gem (100%)
Successfully installed dm-validations-1.2.0
Fetching: bcrypt-ruby-3.1.5.gem (100%)

#######################################################

The bcrypt-ruby gem has changed its name to just bcrypt.  Instead of
installing `bcrypt-ruby`, you should install `bcrypt`.  Please update your
dependencies accordingly.

#######################################################

Successfully installed bcrypt-ruby-3.1.5
Fetching: stringex-1.5.1.gem (100%)
Successfully installed stringex-1.5.1
Fetching: uuidtools-2.1.5.gem (100%)
Successfully installed uuidtools-2.1.5
Fetching: dm-types-1.2.2.gem (100%)
Successfully installed dm-types-1.2.2
Fetching: datamapper-1.2.0.gem (100%)
Successfully installed datamapper-1.2.0
Fetching: data_objects-0.10.14.gem (100%)
Successfully installed data_objects-0.10.14
Fetching: do_postgres-0.10.14.gem (100%)
Building native extensions.  This could take a while...
Successfully installed do_postgres-0.10.14
Fetching: dm-do-adapter-1.2.0.gem (100%)
Successfully installed dm-do-adapter-1.2.0
Fetching: dm-postgres-adapter-1.2.0.gem (100%)
Successfully installed dm-postgres-adapter-1.2.0
Fetching: gitrob-0.0.5.gem (100%)
Successfully installed gitrob-0.0.5
23 gems installed

**Comment by ramschmaerchen** [comment]
I am only a bystander but even for me it is annoying to see people posting issues instead of pull requests. A pull request takes 5 minutes and fixes problems. An issue takes 9 minutes. 4 minutes for you and 5 minutes for the one finally fixing the issue. Especially if the nice author of the application wrote an easy to follow guide of "How to make a pull request":


### How to make a pull request:

1. Fork it ( https://github.com/michenriksen/gitrob/fork )
2. Create your feature branch (`git checkout -b my-new-feature`)
3. Commit your changes (`git commit -am 'Add some feature'`)
4. Push to the branch (`git push origin my-new-feature`)
5. Create a new Pull Request

**Comment by vanhalt** [comment]
```bash
gem server # inside gitrob project
```

You will notice that `dm-types 1.2.2` requires bcrypt-ruby. Even creating a PR here won't solve that message, please check [dm-types gemspec](https://github.com/datamapper/dm-types/blob/master/dm-types.gemspec#L20).

I think that we can close this issue.

**Comment by Choms** [comment]
Hi,
I guess, as I see it fixed on the code, you realized you had to change bcrypt-ruby for bcrypt. Would you mind issuing a new release so when we require this gem we don't get that error message anymore? The latest (dm-types 1.2.2) is still requiring bcrypt-ruby.
Thanks!
