### ISSUE TITLE
Find SSH private keys by content, not only by filename

### ISSUE THREAD

**Issue by pfigue** [michenriksen/gitrob#26]
I have a repository with some private keys: https://github.com/pfigue/gitrob-exciter

The private keys named id_dsa, id_rsa and is_rsa are found without problems, but not those with a different name (e.g. id_rsa2, id_rsa3) are not.

Looking at [patterns.json](https://github.com/michenriksen/gitrob/blob/master/patterns.json) and [sensitive_files.rb](https://github.com/michenriksen/gitrob/blob/master/lib/gitrob/observers/sensitive_files.rb) I see there is no check for the content of the files.

A new check for the content would be useful, so content like this could trigger independently of the filename:

    -----BEGIN RSA PRIVATE KEY-----
    foobar
    -----END RSA PRIVATE KEY-----

**Comment by michenriksen** [comment]
I want to avoid looking into content as it would slow down the tool way too much. Calling private keys *_rsa2 and *_rsa3 is a bit non-standard, but the pattern could be changed to allow a number and maybe things like `id_rsa.old`, `id_rsa.bkp` and so on.

I'm also considering implementing a feature where people can add their own custom patterns in a file like `~/.gitrobpatterns.json` or something, so they don't have to modify the gem code to add private patterns.

**Comment by pfigue** [comment]
*people can add their own custom patterns in a file like ~/.gitrobpatterns.json*

makes sense. Thanks for your reply.
