### ISSUE TITLE
Create a proactive, pre-commit tool?

### ISSUE THREAD

**Issue by maxlinc** [michenriksen/gitrob#28]
Wow, this is a really cool project. Thanks for creating it!

Gitrob appears to be a reactive tool in that it only detects the leak of sensitive data after it has occurred. It could be used to help organizations more quickly detect and fix leaked secrets, but doesn't prevent the data from being leaked in the first place.

It seems like it should be possible to create a tool that uses gitrob's patterns and rules as part of a pre-commit hook so that it could flag a potential leak _before_ it happens. A tool that simply takes a list of files and checks if any of them may violate a gitrob rule would be compatible with yelp's [pre-commit](http://pre-commit.com/) project or other [projects to manage git hooks](http://githooks.com/), making it easy for organizations to use it on multiple projects and on their CI servers.

Note: I do see the value of what gitrob does and why reactive, organization-wide (and beyond) monitoring is a good thing. I'm suggesting a proactive tool as an _addition_ to gitrob's toolchain, not as a change in current behavior.

Basically a CLI tool with a command like `gitrob check [FILES...]` would be useful. I think this would have a many possible advantages:
- Proactive: catch leaks before they happen
- DevOps culture: make it part of the dev toolchain so the devs see when a potential security issue is introduced and can have a conversation with security folks about how to address it or how to mark the commit with a note about a false positive that could be picked up by Gitrob
- Not tied to GitHub: although gitrob's organization-tracking features are definitely github centric, a `gitrob check` tool shouldn't need to assume a project is on github. It could just as easily be used as a pre-commit hook for GitHub alternatives like Bitbucket, Atlassian Stash, or GitLab.
- Not even tied to git: in fact, there's no reason it even needs to assume git. A `gitrob check` command could just as easily be used as a pre-commit for mercurial or other version control systems.
- Client or server-side checking: git supports [client-side or server-side hooks](http://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks). A server-side hook allows the organization to take control and enforce the rules even if the committer has not enabled the hook. This could be done via a pre-receive hook if the org owns the git servers, or on GitHub with via a [webhook](https://help.github.com/articles/about-webhooks/) or [service integration](https://github.com/github/github-services/blob/master/CONTRIBUTING.md). This way an org could set up repos that will either reject commits that contain an apparent security leak that hasn't been explicitly marked as a false positive, or at least send out an alert immediately after the commit happens.
- More intensive checks could be practical: a pre-commit or pre-receive hook has a few advantages over how gitrob currently checks files. First, they know which files have been added/modified so they can speed up the checks by only scanning those files rather than the whole repo. Second, they can easily get a copy of the file content, more quickly and without assuming github than by fetching via raw.githubusercontent.com. So rules that check file content could be faster when run as a hook.

What do you think? Does it make sense, and is it practical, to extract a standalone CLI tool that checks a set of files using the same patterns/rules as gitrob?

**Comment by michenriksen** [comment]
Hi @maxlinc,

It does indeed make a lot of sense! Having a pre-commit/pre-push hook to deny sensitive things ending up in a repository would be a very nice security measure. I looked into creating Git hooks a couple of days ago, but kind of lost my eagerness to do it when I saw the example hooks, haha!

Some of the detection patterns might not be suitable for git hooks, like shell configuration files and such, but the patterns for things that should definitely not end up on GitHub, like private keys, etc. makes a lot of sense to block in a hook.

If you are looking for something that is not bound to any version-control systems, but something that just looks at files in a folder, there is another tool called [blueflower](https://github.com/veorq/blueflower) that you might be interested in.

**Comment by jandre** [comment]
Hey all, I wrote a quick and dirty pre-commit hook that does exactly that. 

https://github.com/jandre/safe-commit-hook

**Comment by mikeatlas** [comment]
+1 for @jandre's tool. Pre-receive hooks via an oauth service in my mind is the most ideal way to handle it: presume accidental fat-fingered pushes from machines lacking local `safe-commit-hook` installed

Only a few more steps further with https://github.com/rvagg/github-webhook-handler and a service could 
be scraped together!

**Comment by tomdavidson** [comment]
I dont think gitrob is the right tool for a pre-commit. On commit I only need the commit (not all the files) looked at, I want file contents not just names to be analyzed, and I want it to be fast. There are tools that do just this:

- pre-commit by yelp
- git-secrets by awslabs
- talisman by thoughtworks
- I have not checked out Jandre's safe-commit-hook.

But I think @mikeatlas has the right idea for a gitrob like service as the last perimeter and to notify admins & devs quickly about the breach. I see a four layer approach with gitrob potentially addressing layer 3 but particularly layer 4:

1. convention and templates - something like put creds outside of git or in .env with .gitignore
2. catch on precommit or prepush at the workstation
3. catch on cicd pipeline
4. reactive web service that checks received code at github, gitlab, etc and notifies the approerate people for quick action
