### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by desax974** [michenriksen/gitrob#29]
Hi 
When i launch gitrob -o "organization name" 
i get an error : SocketError: getaddrinfo : Name or service not know

Anyone can help me please ?

best regards

**Comment by michenriksen** [comment]
Hmm, looks like you have problems with your DNS. What operating system are you on?

**Comment by desax974** [comment]
Ohh Ok sorry for my english i'm come from france .
I'm working on kali linux...

Le 4 févr. 2015 13:11, Michael Henriksen <notifications@github.com> a écrit :
Hmm, looks like you have problems with your DNS. What operating system are you on?

---

**Comment by michenriksen** [comment]
Does it work if you [change your DNS](https://wiki.debian.org/NetworkConfiguration#The_resolv.conf_configuration_file)  to `8.8.8.8`?
