### ISSUE TITLE
gitrob for local repositories / directories ?

### ISSUE THREAD

**Issue by mikerun** [michenriksen/gitrob#31]
I was thinking may be this project could expand to support local repositories or local code directories ?

**Comment by michenriksen** [comment]
Hi @ahmedmg, thanks for your feedback. For now there are no plans to make it work on local repositories, however there is a similar project called [blueflower](https://github.com/veorq/blueflower) which might be of interest to you. It can search a local file system for interesting files and is looking for many of the same things as Gitrob.

Hope that helps!

**Comment by ahmedmg** [comment]
Thanks! didn't know about blueflower it's exactly what I'm looking for if you have any more suggestion it would be great
