### ISSUE TITLE
Enterprise github

### ISSUE THREAD

**Issue by davitb** [michenriksen/gitrob#34]
Is it possible to run gitrob on enterprise github setup?

**Comment by michenriksen** [comment]
Not in its current version, but if the Enterprise API follows the same interface as the official API, it should be pretty straight forward to add an option to specify a different host than `api.github.com`.

I will look into adding this feature. :)

Thanks for your feedback!

**Comment by cdorros** [comment]
Test and see what you think: https://github.com/michenriksen/gitrob/pull/35
I've been running this internally at my org for about a week on GitHub enterprise :)

**Comment by tinsjourney** [comment]
You can do that with a quick workaround, on your host running gitrob, just set the address of your enterprise github as an entry for api.github.com

**Comment by michenriksen** [comment]
A new version of Gitrob is out which supports scanning of custom GitHub Enterprise installations. Unfortunately, I don't have access to a GitHub Enterprise, so I would appreciate if someone could test it out and report any bugs. [Read more here](http://michenriksen.com/blog/new-version-of-gitrob-is-out/).

**Comment by hgautam** [comment]
We are using gitrob version 1.1.0 and running it against our GitHub Enterprise installation and it does not come with any findings :-( I can provide more info if needed. Any help is appreciated.

**Comment by michenriksen** [comment]
Hey @hgautam, It could be that you are simply lucky to not have any files in your repo's that are flagged by Gitrob. :) I would suggest having a look at the [signatures.json](https://github.com/michenriksen/gitrob/blob/master/signatures.json) file and see if anything should have been flagged.

**Comment by hgautam** [comment]
Hi Mike,Thanks for responding. I know for the fact that we have violations present in the files. I even added a mock file full of violations and it still was not flagged. I am looking at some place most likely a log file that tell me what gitrob exactly did. What api calls were made and were the all successful? That kind of stuff. How do I get this info?
Thanks,HimanshuDate: Fri, 15 Apr 2016 01:18:53 -0700
