### ISSUE TITLE
Gitrob not running on Mac OS X

### ISSUE THREAD

**Issue by pvoznenko** [michenriksen/gitrob#37]
Hi @michenriksen ,

Thank you for your tool! 

I can run it on CentOS, but could not manage to make it work on my Mac `10.10.4` with ruby `2.2.2` version and postgres `9.4.4`, keep getting suck error on start: 

```
      _ _           _
  ___|_| |_ ___ ___| |_
 | . | |  _|  _| . | . |
 |_  |_|_| |_| |___|___|
 |___| By @michenriksen

 [*] Starting Gitrob version 0.0.6 at 2015-08-06 05:40 CEST
 [*] Loading configuration... done
 [*] Preparing SQL database... failed
 [!] TypeError: no implicit conversion from nil to integer
```

Maybe you know whats going on? 

Thanks!

**Comment by chuhades** [comment]
i have the same problem, did you solve it?

**Comment by pvoznenko** [comment]
@chuhades unfortunately not, instead used docker container `rgbkrk/gitrob` with own `.gitrobrc` file. 

`Dockerfile` looks like:

```
FROM rgbkrk/gitrob:latest
ADD .gitrobrc /root/
CMD yes | gitrob -s -b 0.0.0.0 -p 9393
```

**Comment by chuhades** [comment]
thanks very much. i'll have a try.



On August 24, 2015 at 6:45:48 PM, Pavlo Voznenko (notifications@github.com) wrote:

@chuhades unfortunately not, instead used docker container rgbkrk/gitrob with own .gitrobrc file.

Dockerfile looks like:

FROM rgbkrk/gitrob:latest
ADD .gitrobrc /root/
CMD yes | gitrob -s -b 0.0.0.0 -p 9393

**Comment by biddster** [comment]
Working fine on ElCap for me:

postgres = 9.4.5 (via homebrew)
ruby = 2.2.3p173 (via homebrew)
gitrob = 0.0.6
