### ISSUE TITLE
add reason/caption/short description to display of findings

### ISSUE THREAD

**Issue by ghost** [michenriksen/gitrob#39]
Environment:  Kali 1.1.0 Linux, Gitrob v0.0.6, Ruby 1.9.1
Priority: Low
Feature request:  When browsing the findings, it would be nice to know the reason why the file was marked as a finding without requiring the file to be opened.  The gitrob_findings.caption database field would be perfect to show.

This really would be rolled up into a feature request "let user change columns to display".

**Comment by michenriksen** [comment]
Hi @ghost, The latest release of Gitrob will now tell you why a file was flagged when hovering. [Read more here](http://michenriksen.com/blog/new-version-of-gitrob-is-out/).
