### ISSUE TITLE
Does not run w/ Ruby 2.2.0

### ISSUE THREAD

**Issue by jfalken** [michenriksen/gitrob#4]
Cannot run with ruby 2.2.0. You get the following error:

```
 [*] Starting Gitrob version 0.0.2 at 2015-01-14 03:12 UTC
 [*] Loading configuration... done
 [*] Preparing SQL database...ruby /home/ubuntu/.rvm/gems/ruby-2.2.0/bin/gitrob: symbol lookup error: /home/ubuntu/.rvm/gems/ruby-2.2.0/extensions/x86_64-linux/2.2.0/do_postgres-0.10.14/do_postgres/do_postgres.so: undefined symbol: rb_thread_select
```

`do_postgres` uses `rb_thread_select` which has been deprecated for a while and was removed from the trunk in v2.2.0. Using 2.1.0 via RVM is a workaround.

see: https://bugs.ruby-lang.org/projects/ruby-trunk/wiki/CAPI_obsolete_definitions and https://github.com/datamapper/do/issues/74

Work around for others:

1. install RVM
2. `rvm install 2.1.0` this will take time
3. `rvm use 2.1.0`
4. `gem install gitrob` ... etc

**Comment by imrehg** [comment]
Confirm this, using 2.1.4 does work.

**Comment by michenriksen** [comment]
Thanks for reporting! I guess there's not much to do about this apart from making an exception in the setup documentation that 2.2.0 is not compatible, until DataMapper is updated.

**Comment by michenriksen** [comment]
I'm now mentioning in the README that version 2.2.0 is currently not compatible.

**Comment by jdickey** [comment]
DataMapper is *very* unlikely to be updated; those who got tired of the ivory-tower runaround without visible progress, have moved on to get [Ruby Object Mapper](http://rom-rb.org/) (ROM) to production quality. That anybody post-early-2013 would actually use DataMapper 1.*x* is a considerable shock, frankly; it has multiple known issues with multiple database engines. What matters here is that DM compatibility with current Postgres broke some time ago and (AFAICT) hasn't been stepped up to by anybody.

**Comment by dentarg** [comment]
I think the problem will go away when @dbussink releases a new version of [do_postgres](https://rubygems.org/gems/do_postgres) with the changes from https://github.com/datamapper/do/pull/77.

**Comment by dbussink** [comment]
> think the problem will go away when @dbussink releases a new version of do_postgres with the changes from datamapper/do#77.

I was planning on doing a release this weekend and did that, so with 0.10.15 it should work now.
