### ISSUE TITLE
Include a Vagrantfile

### ISSUE THREAD

**Issue by sjparkinson** [michenriksen/gitrob#40]
I was thinking of writing a vagrantfile for this project.

Would such a contribution be worth a PR? If so I'll get something together.

**Comment by stefancocora** [comment]
:+1: 
A `Vagrantfile` will make trying this tool a lot more streamlined !

**Comment by sjparkinson** [comment]
Potentially superseded by #43. The hard works been done there, perhaps this should be closed and some of @mikeatlas work be opened as a PR.
