### ISSUE TITLE
Needed to also install postgresql-server-dev package

### ISSUE THREAD

**Issue by imrehg** [michenriksen/gitrob#5]
According to the docs, only the `libpq-dev` package is required for development headers. Found that also need a server dev header package too, e.g. `postgresql-server-dev-all`. (otherwise end up with missing `postgres.h` and gitrub config fails)

Using Ubuntu 14.10 x86 version.

**Comment by d-oliveros** [comment]
I can confirm this. In my case, I had to install `postgresql-server-dev-9.4`.

**Comment by michenriksen** [comment]
Thanks for reporting, I'll look into it and update the documentation.

**Comment by vanhalt** [comment]
I can confirm the issue. Even in kali I had to run
```bash
apt-get install postgresql-server-dev-9.1
```
Kali brings the 9.1 version by default.

**Comment by michenriksen** [comment]
I tried setting up Gitrob in a totally fresh installation of Kali version 1.0.9a and actually didn't need to install any packages to get it up and running. However, I have modified the readme to mention that it might be necessary to install `postgresql-server-dev-9.1` in Kali.

**Comment by Shekharrajak** [comment]
I get an error 

> The following packages have unmet dependencies:
>  postgresql-server-dev-9.1 : Depends: libpq-dev (>= 9.1~) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
>
