### ISSUE TITLE
Ability to specify the git branch

### ISSUE THREAD

**Issue by biddster** [michenriksen/gitrob#50]
It seems to me that GitRob is inspecting the master branches. We use GitFlow so I'd really like to be able to able to interrogate the development branch every time someone pushes to it.

**Comment by biddster** [comment]
It would be pretty cool, I think, if this was one of the command line switches.

**Comment by michenriksen** [comment]
Hi @biddster, The new version of Gitrob picks the branch that was set as the primary branch for a repository. [Read more here](http://michenriksen.com/blog/new-version-of-gitrob-is-out/).
