### ISSUE TITLE
scan standalone git repositories

### ISSUE THREAD

**Issue by mr-future** [michenriksen/gitrob#51]
Hi,

Is it possible to use gitrob to scan a single Git repository that is not in GitHub?

Thanks,
Brandt

**Comment by michenriksen** [comment]
Hi @mr-future, The new version of Gitrob allows you to scan a single user. I guess this could work for now. I might look into single repository analysis in a later release. [Read more](http://michenriksen.com/blog/new-version-of-gitrob-is-out/) about the new release here.

**Comment by mr-future** [comment]
Hi Michael,

First, very exciting about the new release! About my request – I wasn’t clear about what I actually meant. My company uses GitBucket. I am wondering if it is possible to scan any git repository (Github or not) by cloning it with ssh, then scanning it. Or manually cloning a repository and then pointing gitrob at it. Please let me know if it is possible to do this.

Thanks,
Brandt
