### ISSUE TITLE
Private Org repositories don't seem to be found

### ISSUE THREAD

**Issue by jstoneky** [michenriksen/gitrob#53]
<img width="720" alt="screen shot 2016-03-16 at 8 52 15 pm" src="https://cloud.githubusercontent.com/assets/2001280/13833958/03483624-ebb9-11e5-95ef-bdf472ba457e.png">

**Comment by michenriksen** [comment]
Hi @jstoneky, thanks for reporting. I'm using the `github_api` Gem to talk to the API, don't know why it wouldn't return private repo's if you have access to them. I will see if I can do something differently.

**Comment by michenriksen** [comment]
I have pushed a fix to this problem. It will be part of the next release.

**Comment by jstoneky** [comment]
Awesome, thanks. Is it in master?

**Comment by michenriksen** [comment]
It is. If you want it now, you can install it in your system with `rake install`.

**Comment by jstoneky** [comment]
confirmed it working for private repos. Thanks

**Comment by michenriksen** [comment]
Fixed in version [1.0.1](https://github.com/michenriksen/gitrob/blob/master/CHANGELOG.md#101)
