### ISSUE TITLE
request: scanning file content for secrets

### ISSUE THREAD

**Issue by feradi** [michenriksen/gitrob#54]
Hi @michenriksen,

thank you for the great work in the first place! 
I'd be very interested to know if you are planning to scan the content of files also

**Comment by michenriksen** [comment]
Hi @feradi, thanks for the kind words.

For now I am not planning on making Gitrob scan file contents as I think it would take an impractical amount of time and require a lot of API requests. 

If you would like to search for sensitive file content, you can clone repositories of interest and scan the directories with another awesome tool called [blueflower](https://github.com/veorq/blueflower).

Hope that helps!
