### ISSUE TITLE
Inclusion of Signatures in SecLists

### ISSUE THREAD

**Issue by danielmiessler** [michenriksen/gitrob#56]
Hey there, was wondering if it'd be ok for me to include your signatures file (probably not in the same format) in the SecLists project.

I'm collecting all the different checks of this type into one place so arbitrary engines can query for all of these types of things.

https://github.com/danielmiessler/SecLists/ 

Thanks!

**Comment by michenriksen** [comment]
Sure, no problem! Thanks for SecLists, btw. It's awesome.
