### ISSUE TITLE
Signatures.json

### ISSUE THREAD

**Issue by danielmiessler** [michenriksen/gitrob#57]
Hi Michael,

Wondering if I can use your signatures.json file for a couple of other projects. It'll be added to a collection of other similar signatures, plus others for finding coding flaws. 

The projects will be SecLists and another that's yet to be named.

Let me know and I'll add you to the credits!

Thanks,

Daniel

**Comment by michenriksen** [comment]
Hi @danielmiessler, That is all fine by me. Gitrob is released under the MIT license so go ahead and use whatever you want! A credit is of course very appreciated.

Would you mind pinging me when your secret project is done? It sounds interesting and I would like to merge any signature additions into Gitrob if that is OK with you?

Cheers,
Michael

**Comment by danielmiessler** [comment]
Absolutely!

**Comment by michenriksen** [comment]
Hey, I was wondering when I can expect to see the credit? SecLists is a pretty popular and awesome resource, and I think it could drive some attention to Gitrob which would be cool. :)
