### ISSUE TITLE
.env files?

### ISSUE THREAD

**Issue by Skeyelab** [michenriksen/gitrob#58]
We use .env files.  Can gitrob be setup to flag these files?

**Comment by michenriksen** [comment]
Hi @Skeyelab, that is definitely possible! I was actually surprised I didn't have a signature for this yet, I was sure Gitrob already looked for these files.

I will add in this signature, thanks for letting me know!

**Comment by Skeyelab** [comment]
Thanks.  Another nice option would be able to define our own signatures somehow.

**Comment by michenriksen** [comment]
Yes, a couple of people have been asking for this feature. It makes sense if you have file signatures that are very specific for your organisation. But I hope people will still create Pull Requests to Gitrob if they have signatures that would benefit everyone.

I'll look into adding this feature.

**Comment by michenriksen** [comment]
Hi @Skeyelab, I have just released version 1.1.0 which includes a signature for `.env` files as well as the ability to define custom signatures.

To get the latest version, simply run `gem update gitrob` in a terminal and read [this section](https://github.com/michenriksen/gitrob#adding-custom-signatures) of the README on how to add custom signatures.

Enjoy and let me know if you find any issues with the new version!
