### ISSUE TITLE
No files/findings for github enterprise.

### ISSUE THREAD

**Issue by crimsonknave** [michenriksen/gitrob#61]
When I use gitrob against github.com things seem to work fine, however, when I point it at my enterprise github it does not list any files or findings.

I'm calling it like so:
```gitrob analyze jhenrich --site=https://github.acme.com --endpoint=https://github.acme.com/api/v3```

I do not see any errors in the output, all the repositories are found, but there is nothing in the repos.

I'm using v1.1.0

**Comment by michenriksen** [comment]
Hi @crimsonknave, debugging problems with GitHub Enterprise installations is unfortunately a little difficult for me as I don't have access to an installation.

If you run Gitrob like this:

    DEBUG=1 gitrob analyze jhenrich --site=https://github.acme.com --endpoint=https://github.acme.com/api/v3

You should see details of the HTTP request and responses from the github_api gem. Do you see any `404`s or something when it starts fetching repository content?

**Comment by michenriksen** [comment]
I have asked GitHub Enterprise Support if it's possible for me to get a trial installation so I can verify that everything works against GitHub Enterprise. Let's see what they say.

I would of course still appreciate any comments from you folks if you figure out what the problem might be or if you have any interesting output from Gitrob.

Thanks!

**Comment by hgautam** [comment]
Thanks Mike. I just see bunch of sql commands in std out. Are there any details logs anywhere that can tell me more?I would be happy to debug this more. Any pointers appreciated.
Thanks,HimanshuDate: Sun, 17 Apr 2016 09:09:47 -0700

**Comment by michenriksen** [comment]
@hgautam could try to run Gitrob with `DEBUG=1 gitrob analyze ...`? Then you should see request/response information from the github_api gem. It would be interesting to see the response could when Gitrob fetches repository contents.

Thanks!

**Comment by crimsonknave** [comment]
I only see three statuses printed in the debug. It looks like /user?access_token, /user/repos and a second page of repos. After that I see it printing the connection options and an info about a call to each repo, but never the payload or response code.

When I run against public github I see the status printed out for each repo.

I know that our version of github enterprise is a bit old, but I can't find a version anywhere. But, I wouldn't expect that to break anything like this. It is responding on the v3 api url so it's not *that* old.

**Comment by hgautam** [comment]
Hi Joseph,We upgraded to GH enterprise 2.5.4 over the weekend. Ran gitrob analyze with debug option on the newer version and I dont see response code or payload either.
Please let me know if you guys want me to run any other test commands or capture any logs etc.
Appreciate your help.
-HimanshuDate: Mon, 18 Apr 2016 08:14:15 -0700

**Comment by osok** [comment]
I'm having a similar problem.  I noticed that the gathering targets does a GET on /users/xxx

meaning the url should be
https://github.mycompany.com/users/xxx

however the actual URL is
https://github.mycompany.com/xxx

So I get an error:

Gathering targets...EXECUTED: get - /users/xxx with PARAMS: {} failed
[!] Faraday::TimeoutError: Connection timed out - connect(2)
[!] No users or organizations found; exiting

**Comment by osok** [comment]
I should add that I'm running UBUNTU
Linux ip-10-206-4-240 3.13.0-83-generic #127-Ubuntu SMP Fri Mar 11 00:25:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

and I built the the server and the GitRob app today.

**Comment by osok** [comment]
I had to list a valid endpoint on the commandline and then it took off running.

**Comment by crimsonknave** [comment]
So, @michenriksen, I figured it out! It all works if I add a / after v3. 

```
--endpoint=https://github.roving.com/api/v3/
```

It would be nice if there'd been some sort of error in the output. Even with debug enabled I don't see anything indicating that it got a 404 back from github.

**Comment by osok** [comment]
I have it running too against an enterprise github server.  I ran it with the 

`DEBUG=1 gitrob analyze.....`

and I think I found the problem.....

after the   .../api/v3 there should be a forward slash before repos when it is looking at the repo.  its missing.  I copied the URL out and tried it in a browser and got essentially a 404.  then I inserted the / and got a lot more data back.  Looks like the file list.

**Comment by michenriksen** [comment]
@crimsonknave, @osok: Wow, thanks a ton for your help and figuring out the problem. This is awesome! I'm happy that you got it working for you.

It sounds like a pretty easy fix. I will look into implementing it as soon as I have some time.

I haven't heard back from GitHub yet regarding getting access to a GitHub Enterprise installation, but hopefully I will get access to one soon, so I can help with debugging these problems.

Cheers,

**Comment by hgautam** [comment]
That did it for me to. Just added a / after api/v3/ and i see flagged material now.
Thanks for all your help. However, I didn't see see any error in the debug output indicating this might be the problem. How did you even figure this out?
Thanks,HimanshuDate: Wed, 20 Apr 2016 13:10:36 -0700

**Comment by mrmanc** [comment]
I think I experienced this issue because I copy pasted the URL format for the API from the README. Would it be a good idea to change `--endpoint=https://github.acme.com/api/v3` to `--endpoint=https://github.acme.com/api/v3/` on [this line](https://github.com/michenriksen/gitrob/blame/master/README.md#L73)?
