### ISSUE TITLE
gem install gitrob. Failed to build gem native extension.

### ISSUE THREAD

**Issue by binarymist** [michenriksen/gitrob#62]
Is this a known issue?
This was my install process on kali 2016.1. Did I miss something? Thanks:

1. `git clone https://github.com/michenriksen/gitrob.git`
2. `gem install bundler`
3. `service postgresql start`
4. `su postgres`
5. `createuser -s  gitrob  --pwprompt`
6. `createdb -O gitrob gitrob`
7. `exit`
8. `cd /opt/gitrob/bin`
9. `gem install gitrob`

Output:

# gem install gitrob
Fetching: thread-0.2.2.gem (100%)
Successfully installed thread-0.2.2
Fetching: concurrent-ruby-1.0.1.gem (100%)
Successfully installed concurrent-ruby-1.0.1
Fetching: sucker_punch-2.0.1.gem (100%)
Sucker Punch v2.0 introduces backwards-incompatible changes.
Please see https://github.com/brandonhilkert/sucker_punch/blob/master/CHANGES.md#20 for details.
Successfully installed sucker_punch-2.0.1
Fetching: sequel-4.33.0.gem (100%)
Successfully installed sequel-4.33.0
Fetching: ruby-progressbar-1.7.5.gem (100%)
Successfully installed ruby-progressbar-1.7.5
Fetching: pg-0.18.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing gitrob:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/pg-0.18.4/ext
/usr/bin/ruby2.3 -r ./siteconf20160416-30152-1wr2ior.rb extconf.rb
checking for pg_config... yes
Using config values from /usr/bin/pg_config
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
You need to install postgresql-server-dev-X.Y for building a server-side extension or libpq-dev for building a client-side application.
checking for libpq-fe.h... no
Can't find the 'libpq-fe.h header
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--with-pg
	--without-pg
	--enable-windows-cross
	--disable-windows-cross
	--with-pg-config
	--without-pg-config
	--with-pg_config
	--without-pg_config
	--with-pg-dir
	--without-pg-dir
	--with-pg-include
	--without-pg-include=${pg-dir}/include
	--with-pg-lib
	--without-pg-lib=${pg-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/pg-0.18.4 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4/gem_make.out

Doesn't appear to be anything extra in the /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/pg-0.18.4/gem_make.out

**Comment by michenriksen** [comment]
Hi @binarymist, 

It looks like you might need to do a quick `apt-get install libpq-dev` and try again.

Which version of Kali are you installing it on?

**Comment by binarymist** [comment]
2016.1 rolling

**Comment by rajuXkiran** [comment]
Hi,
I am trying to install gitrob on CentOS 7,i followed the installation Guide on github but iam getting the below error while installing.

[root@localhost ~]# gem install gitrob
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: colorize-0.8.1.gem (100%)
Successfully installed colorize-0.8.1
Fetching: highline-1.7.8.gem (100%)
Successfully installed highline-1.7.8
Fetching: thread-0.2.2.gem (100%)
Successfully installed thread-0.2.2
Fetching: ruby-progressbar-1.8.1.gem (100%)
Successfully installed ruby-progressbar-1.8.1
Fetching: rack-1.6.4.gem (100%)
Successfully installed rack-1.6.4
Fetching: tilt-2.0.5.gem (100%)
Successfully installed tilt-2.0.5
Fetching: rack-protection-1.5.3.gem (100%)
Successfully installed rack-protection-1.5.3
Fetching: sinatra-1.4.7.gem (100%)
Successfully installed sinatra-1.4.7
Fetching: eventmachine-1.2.0.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing gitrob:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/share/gems/gems/eventmachine-1.2.0.1/ext
/usr/bin/ruby -r ./siteconf20161109-6271-3emepx.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/share/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /usr/local/share/gems/gems/eventmachine-1.2.0.1 for inspection.
Results logged to /usr/local/lib64/gems/ruby/eventmachine-1.2.0.1/gem_make.out

**Comment by HassanKhanYusufzai** [comment]
Hi,
For me issue solved with the following steps.

1- sudo apt-get install ruby-full
2- sudo apt-get install libz-dev libiconv-hook1 libiconv-hook-dev
3- sudo gem install rails
4- gem install gitrob

I hope this will help.

**Comment by mikkz** [comment]
Hi,

I got errors when trying to fix this with `apt-get install libpq-dev`

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libpq-dev : Depends: libpq5 (= 9.6.3-1.pgdg12.4+1) but 9.6.2-2 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by noobsecX01** [comment]
@mlkkz same here i can't able to install libpq-dev in kali sana
i try to fix but it get worst, i heck my repo ,every thing fine but still i get stuck in this step

**Comment by yash2707** [comment]
> Hi @binarymist,
> 
> It looks like you might need to do a quick `apt-get install libpq-dev` and try again.
> 
> i did this part 
when i redo the whole process it shows "could not change directory to "/root": Permission denied"
What should I should do?

**Comment by preethamarun00** [comment]
Check with commonds  that chmod+777 or get wr-rw-ro
