### ISSUE TITLE
gitrob configure failing with bad URI

### ISSUE THREAD

**Issue by binarymist** [michenriksen/gitrob#63]
Hi.

`gitrob configure`

 ___|_| |_ ___ ___| |_
| . | |  _|  _| . | . |
|_  |_|_| |_| |___|___|
|___| By @michenriksen

[*] Starting Gitrob version 1.1.0 at 2016-04-17 12:21 NZST
[*] Starting Gitrob configuration wizard
Enter PostgreSQL hostname: |localhost| 
Enter PostgreSQL port: |5432| 
Enter PostgreSQL username: |gitrob| 
Enter PostgreSQL password (masked): xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Enter PostgreSQL database name: |gitrob| 
Enter GitHub access tokens (blank line to stop):
<my access token>

[*] Saving configuration to /root/.gitrobrc done
[*] Loading configuration... done
[*] Preparing database... failed
[!] URI::InvalidURIError: bad URI(is not URI?): postgres://gitrob:o[7&MI).@c@localhost:5432/gitrob

&nbsp;
&nbsp;
postgresql is running on localhost and listening on 5432
&nbsp;

ss -ant
State      Recv-Q Send-Q                                            Local Address:Port                                                           Peer Address:Port              
LISTEN     0      128                                                   127.0.0.1:5432                                                                      *:*                  
ESTAB      0      0                                                     <vboxnatip>:42772                                                         192.30.252.91:443                
CLOSE-WAIT 1      0                                                     <vboxnatip>:39326                                                         52.71.215.230:443                
CLOSE-WAIT 1      0                                                     <vboxnatip>:40460                                                       103.245.222.133:443                
CLOSE-WAIT 1      0                                                     <vboxnatip>:39236                                                        192.30.252.121:443                
CLOSE-WAIT 1      0                                                     <vboxnatip>:40458                                                       103.245.222.133:443                
CLOSE-WAIT 0      0                                                     <vboxnatip>:40464                                                       103.245.222.133:443                
CLOSE-WAIT 290    0                                                     <vboxnatip>:40514                                                       103.245.222.133:443                
CLOSE-WAIT 0      0                                                     <vboxnatip>:40462                                                       103.245.222.133:443                
CLOSE-WAIT 0      0                                                     <vboxnatip>:40466                                                       103.245.222.133:443                
CLOSE-WAIT 1      0                                                     <vboxnatip>:47948                                                        192.30.252.126:443                
ESTAB      0      0                                                     <vboxnatip>:38170                                                         216.58.199.46:443                
CLOSE-WAIT 13     0                                                   <vboxbridgedip>:46696                                                          <switchip>:445                
CLOSE-WAIT 290    0                                                     <vboxnatip>:40512                                                       103.245.222.133:443                
LISTEN     0      128                                                         ::1:5432                                                                     :::*                  
CLOSE-WAIT 171    0                                                           ::1:34786                                                                   ::1:5432               
ESTAB      0      0                                                           ::1:5432                                                                    ::1:37390              
ESTAB      0      0                                                           ::1:37390                                                                   ::1:5432

**Comment by michenriksen** [comment]
I guess the problem is because the postgresql password contains an `@` sign, which causes the connection URI (`postgres://<username>:<password>@<host>:<port>/<database>`) to be invalid.

I'll look into a way to escape `@` signs when constructing the connection URI. In the meantime, you can fix it by removing it from the password.

**Comment by binarymist** [comment]
That's it. Didn't recognise the password due to being in a password database which allows me to never have to look at them.
