### ISSUE TITLE
Gitrob: Command not found

### ISSUE THREAD

**Issue by chackokavanattu12** [michenriksen/gitrob#68]
Hi michenriksen

I have followed the installation steps given, I am running a kali machine, I have ruby 2.1.5, have postgresql service started with client version 9.4.3,Have created gitrob users and databases, Installed gitrob gem pulled the svn co https://github.com/michenriksen/gitrob etc.

Now when i trying to use "gitrob configure" or "gitrob --configure" its giving me the following issue.
root@kali:/# gitrob configure
bash: gitrob: command not found
root@kali:/# gitrob --configure
bash: gitrob: command not found

Could you please help me understand what the issue is all about and have i dont any mistake on this. Please help i am installing this for my company. Would be helpful if you could help me

**Comment by michenriksen** [comment]
Hey there,

Did you install Ruby with RVM or are you using the default Ruby installation in Kali?

**Comment by chackokavanattu12** [comment]
Using default ruby, should I use rvm??

**Comment by michenriksen** [comment]
No, the default Ruby in Kali should be fine. It must be because the path to executables that are installed by rubygems is not part of your `$PATH`. What do get back if you do `echo $PATH` in a terminal?

**Comment by chackokavanattu12** [comment]
Hi Micheal

[image: Inline image 1]

**Comment by chackokavanattu12** [comment]
This is what i get 

root@kali:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by chackokavanattu12** [comment]
Is there a issue where i have multiple python enviornments running i have python 2.7 and python 3.4 as well .

**Comment by michenriksen** [comment]
Hmm... If I do `gem install gitrob` in a vanilla Kali installation, it installs the gitrob executable at `/usr/local/bin/gitrob` which is part of the $PATH.

Do you find any gitrob executable if you do `find / -type f -executable -name gitrob` in a terminal?

**Comment by chackokavanattu12** [comment]
Hi Micheal

Yes it is there i see the executables,But Not sure what went wrong what i
just now did was removed the python virtual enviornment placed only one
python version that is default 2.7 and apt-get update and then started my
postgresql service and now ran gitrob configure and  now it started
working,

Also one other question i had is that if i were to scan the private repo's
of my organization, i should have

1. I should be a member of my organization
2. I should also have access to the private repositories

Am i correct on this statements that i have made that would scan even my
private and internal repo's?



On Wed, May 25, 2016 at 3:38 PM, Michael Henriksen <notifications@github.com

**Comment by michenriksen** [comment]
Good to hear that you figured it out!

yes, the owner of the API key you use will need to be a member of the organization and have access to the private repositories you want to scan. Also remember the correct permission scopes for the key: It needs `repo` and `read:org`.

**Comment by chackokavanattu12** [comment]
Thanks Michael, That Helped a lot and your tool the latest version is real
good.

Thanks


On Wed, May 25, 2016 at 5:15 PM, Michael Henriksen <notifications@github.com
