### ISSUE TITLE
tokens from multiple accounts

### ISSUE THREAD

**Issue by matkoniecz** [michenriksen/gitrob#69]
> If you plan on using Gitrob extensively or against a very large organization, it might be necessary to have multiple access tokens to avoid running into rate limiting. These access tokens will have to be from different user accounts.

It sounds like something that would be against Github ToS - at least some time ago it was against ToS to have multiple accounts.

Maybe it would be a good idea to explicitly note whatever something like that would violate Github ToS?

**Comment by michenriksen** [comment]
Yes, you are correct. It looks like it's still against the ToS:

    One person or legal entity may not maintain more than one free account, and one machine user account that is used exclusively for performing automated tasks.

What I mean in the README is mainly for companies where several employees can generate an access token for Gitrob. If several individuals generate an access token to be used for scanning their own GitHub Org, it should not violate the ToS as far as I understand.

It's a good suggestion to add a notice and a link to the ToS though, I will look into that.
