### ISSUE TITLE
Server Error 500: NoMethodError - undefined method `join' for nil:NilClass

### ISSUE THREAD

**Issue by tomdavidson** [michenriksen/gitrob#71]
gitrob server appears to starts just fine, but when it receives web traffic (initial page load) an error is displayed in the browser as well as the console.  

**Reproduction Steps:**
1. clone [repo](https://gitlab.com/librelabs/docker-gitrob/tree/master)
2. docker-compose up
3. http://127.0.0.1:9393

**Expected behavior:**
Expected error free webui that would allow me to scan my github orgs.... and do all of my work for me.

**Observed behavior:**
Internal Server Error 500 with this debug info - [gist](https://gist.github.com/tomdavidson/0442b45d45f846f7f21393403068f5eb). 
At the console I observed essentially the same - [gist](https://gist.github.com/tomdavidson/c70affb853279a17a70d1ed0fef85cf6).

**Gitrob version:** 1.1.0
**OS and version:** Debian 8.5
**Ruby version:** 2.3
**PostgreSQL version:** 9.5.3
**Base Docker image:** ruby:2.3

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Gitrob: na
- Problem can be reliably reproduced, doesn't happen randomly: yes
- Problem happens with all assessments, not only some assessments: na

**Comment by michenriksen** [comment]
Hi Tom, thanks for reporting and using the bug report template!

It looks like the issue might be because Gitrob hasn't been configured with any GitHub access tokens. Do you see any if you `cat ~/.gitrobrc`? If not, just run `gitrob configure` and give it some access tokens.

**Comment by tomdavidson** [comment]
thank you for the quick reply. Is my usage of --access-tokens in my entrypoint [script](https://gitlab.com/librelabs/docker-gitrob/blob/master/run.sh#L14) incorrect?

```
exec gitrob server \
--access-tokens=$GITHUB_TOKENS \
--bind-address=$GITROB_SERVER_ADDRESS \
--port=$GITROB_SERVER_PORT
```

$GITHUB_TOKENS is set from my .env file and looks like:
`GITHUB_TOKENS=ba86b6249ff2ae8fa33a3f6292e4b182`


Since I am trying to use --access-tokens & env vars, I have not put the creds in the .gitrobrc file:
```
root@5a02382105c6:/# cat ~/.gitrobrc 
---
sql_connection_uri: postgres://postgres:mysecretpassword@db:5432/gitrob
```

**Comment by tomdavidson** [comment]
I recently tried again, this time adding the access tokes to the .gitrobrc file and still has the same symptoms.

**Comment by Sliim** [comment]
Try putting your github access token in an array, this is what I have in my gitrobrc:
```
---
sql_connection_uri: postgres://postgresql/gitrob
github_access_tokens: [mytoken]
```
