### ISSUE TITLE
Pulling out Reports 

### ISSUE THREAD

**Issue by chackokavanattu12** [michenriksen/gitrob#73]
Hi Micheal 

Is there any feature in gitrob to pull out the information as a report?  or any plans to do that. Its quite tough to keep the check on the browser.

**Comment by michenriksen** [comment]
Hi there,

Currently there is no way to generate a report of the findings. A possibility might be to print the pages in the web app as PDFs, but you could also do some coding around the data as everything can be found in the Postgresql database, so you could script something that would generate the kind of report you are looking for.

What sort of report did you imagine? A PDF, CSV, JSON or something else? Report feature has been suggested before so I might look into implementing something. I just need to know a bit more what people would like. :)

**Comment by chackokavanattu12** [comment]
Hi Micheal

A PDF and CSV  would be great. Yeah i was thinking of printing the pages as
PDF as of now.

Thanks
Chacko

On Fri, Jun 24, 2016 at 8:25 PM, Michael Henriksen <notifications@github.com

**Comment by chackokavanattu12** [comment]
Hi Micheal

One more suggestion Micheal is that it would be great if there is a
function that i can check telling that this finding is a fals positive and
can remove them and then can concentrate if anything new has come up.

Thanks & Regards
Chacko Abraham

**Comment by nigifabio** [comment]
I would like to add as option a --syslog or --file to dump the finding in text and be used in automated envirment as well (logstash or splunk etc)
