### ISSUE TITLE
Issues running "gitrob configure" after installation

### ISSUE THREAD

**Issue by ortizmj12** [michenriksen/gitrob#77]
I'm having issues configuring gitrob after I install it. I'm getting this error:

```
$ gitrob configure
/home/mortiz/.gem/ruby/gems/github_api-0.14.3/lib/github_api/api.rb:301:in `namespace': namespace 'say' is already defined (ArgumentError)
    from /home/mortiz/.gem/ruby/gems/github_api-0.14.3/lib/github_api/client.rb:61:in `<class:Client>'
    from /home/mortiz/.gem/ruby/gems/github_api-0.14.3/lib/github_api/client.rb:4:in `<module:Github>'
    from /home/mortiz/.gem/ruby/gems/github_api-0.14.3/lib/github_api/client.rb:3:in `<top (required)>'
    from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/mortiz/.gem/ruby/gems/github_api-0.14.3/lib/github_api.rb:78:in `block in require_all'
    from /home/mortiz/.gem/ruby/gems/github_api-0.14.3/lib/github_api.rb:77:in `each'
    from /home/mortiz/.gem/ruby/gems/github_api-0.14.3/lib/github_api.rb:77:in `require_all'
    from /home/mortiz/.gem/ruby/gems/github_api-0.14.3/lib/github_api.rb:113:in `<module:Github>'
    from /home/mortiz/.gem/ruby/gems/github_api-0.14.3/lib/github_api.rb:15:in `<top (required)>'
    from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/mortiz/.gem/ruby/gems/gitrob-1.1.0/lib/gitrob.rb:9:in `<top (required)>'
    from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /home/mortiz/.gem/ruby/gems/gitrob-1.1.0/exe/gitrob:3:in `<top (required)>'
    from /usr/local/bin/gitrob:22:in `load'
    from /usr/local/bin/gitrob:22:in `<main>'
```

**Comment by ortizmj12** [comment]
I was talking to a friend about this and he found a solution [here](https://github.com/michenriksen/gitrob/issues/74#issuecomment-230745132).

**Comment by johnconner31** [comment]
I am having same error and tried to edit the file as mentioned in referenced link, but didnt' found any namespace argument commenting on 61 line? Could you help me out if you managed it to work on your box?

error i am getting is: 

> /var/lib/gems/2.3.0/gems/github_api-0.14.4/lib/github_api/api.rb:301:in `namespace': namespace 'say' is already defined (ArgumentError)
	from /var/lib/gems/2.3.0/gems/github_api-0.14.4/lib/github_api/client.rb:61:in `<class:Client>'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.4/lib/github_api/client.rb:4:in `<module:Github>'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.4/lib/github_api/client.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.4/lib/github_api.rb:78:in `block in require_all'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.4/lib/github_api.rb:77:in `each'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.4/lib/github_api.rb:77:in `require_all'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.4/lib/github_api.rb:113:in `<module:Github>'
	from /var/lib/gems/2.3.0/gems/github_api-0.14.4/lib/github_api.rb:15:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/lib/gitrob.rb:9:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/gitrob-1.1.0/exe/gitrob:3:in `<top (required)>'
	from /usr/local/bin/gitrob:23:in `load'
	from /usr/local/bin/gitrob:23:in `<main>'

**Comment by sabsowitz** [comment]
Go to:
`/usr/local/lib/ruby/gems/2.3.0/gems/github_api-0.14.3/lib/github_api/client.rb` 

And comment out around line 61:
`
    namespace :repos
    alias :repositories :repos

    # namespace :say
    alias :octocat :say

    namespace :scopes`
