### ISSUE TITLE
 NoMethodError: undefined method `[]' for #<Github::Client:0x00000001a8c950>

### ISSUE THREAD

**Issue by johnconner31** [michenriksen/gitrob#79]
Hi,
getting this error while running `gitrob analyze org-name` . Can anybody help me out? Thanks!

[_] Loading signatures... done
[_] Loaded 79 signatures
[_] Gathering targets... failed
[!] NoMethodError: undefined method `[]' for #Github::Client:0x00000001a8c950
[_] Gathering repositories from 1 targets...
[*] Progress 1/1 |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| 100% Time: 00:00:00
[!] No repositories found; exiting

**Comment by zimzima** [comment]
I'm having the same problem, did you find a way around it?

**Comment by victor-domain** [comment]
Same here..

**Comment by zimzima** [comment]
The solution provided by kieran-combes works great: 
gem uninstall github_api
gem install github_api -v 0.13

I hope that helps

**Comment by johnconner31** [comment]
@zimzima Thanks, it worked.

**Comment by anshumanbh** [comment]
This does not work even with github_api -v 0.13. I still get the same error

> 
[*] Loading signatures... done
[*] Loaded 79 signatures
[*] Gathering targets... failed
[!] NoMethodError: undefined method `[]' for #<Github::Client:0x005558a0674640>

**Comment by anshumanbh** [comment]
So, I figured that the above error is caused due to the API key being used. I was using an overly permissible API key of my github organization that sits behind a VPN. I replaced that by my personal account's key and it started working
