### ISSUE TITLE
Gathering Targets Failed

### ISSUE THREAD

**Issue by arbazhussain149** [michenriksen/gitrob#82]
![git](https://cloud.githubusercontent.com/assets/13177578/17084786/de06756e-51e4-11e6-9575-1e96799a9133.PNG)

**Comment by zimzima** [comment]
I'm having the same issue, any news?

**Comment by kieran-combes** [comment]
`gem uninstall github_api`
`gem install github_api -v 0.13`

fixed it for me

**Comment by arbazhussain149** [comment]
Thanks for You'r Valuable Solution It Work's , @kieran-combes  , Closing Report As Resolved !
