### ISSUE TITLE
Ability to configure gitrob not to search through repositories outside the organisation

### ISSUE THREAD

**Issue by vinsf** [michenriksen/gitrob#84]
I have been using gitrob to search for files in my organisations github accounts but I have been finding many more things that I wanted to find. Gitrob fetches all users from those accounts and then fetches the repositories from those users too.

While this is good in a way it can also become a problem if too much is found in these other repositories.

Is there a way to disable this or can we implement na option to disable it at run time?

I am happy to work on the code if pointed to the right place.

**Comment by michenriksen** [comment]
Hi there,

Currently Gitrob doesn't support ignoring organization members, but it should be pretty easy to add a command like flag like `--no-org-members` to skip them. I see what you mean with the problem of "information overload" when analyzing Org members, but also keep in mind that you can have some serious blindspots if ignoring those, as an engineer's `.bashrc`, `.bash_history` and similar files can potentially contain pretty devastating information disclosure.

Cheers,
Mike
