### ISSUE TITLE
Gitrob analysis on a single repository

### ISSUE THREAD

**Issue by hgautam** [michenriksen/gitrob#85]
Hi,
As per documentation, Gitrob can analyze orgs or users. I have a use case where I want to run this for a particular repository. Does the tool allow this or it only works with orgs and user names?

Thanks,
HG

**Comment by michenriksen** [comment]
Hi there,

Currently Gitrob doesn't support analyzing a single repository, but it would be a nice addition to the tool. I will add it to the list of new features to implement.

Thanks!
