### ISSUE TITLE
Multiple instances of Gitrob

### ISSUE THREAD

**Issue by andrewhzhang** [michenriksen/gitrob#86]
Is there a way to have multiple instances or maybe just a way to have more than one type of scan? Currently I'm doing a scan of both public and private repos for an organization but both scans are combined in the same database in PostgreSQL. 

I think it would be useful to have a feature where you can do separate scans that separate the results into two or more databases so you can easily pull data from the one that you want. Thanks.

**Comment by michenriksen** [comment]
Hi Andrew,

Curently Gitrob does not support easy switching between databases, however a solution I can see right now would be to have a folder with two different `.gitrobrc` files which each have a different database connection URI. You can then switch between the two by creating symbolic links, e.g.:

    $ ln -s gitrob_configs/gitrobrc_db1 .gitrobrc
    $ gitrob analyze org1
    $ unlink .gitrobrc
    $ ln -s gitrob_configs/gitrobrc_db2 .gitrobrc
    $ gitrob analyze org2

I will add a way to specify a .gitrobrc location with a `--config` flag to the list of features to add.

Cheers,
Mike
