### ISSUE TITLE
Stop/Start/Restart GitRob command.

### ISSUE THREAD

**Issue by HanisHairuddin** [michenriksen/gitrob#87]
Hi All,

Is there a proper command to stop/start or restart GitRob server?

I'm trying to automate the GitRob scanning capabilities. I've managed to done some scripting and add them into crontab for daily runs.

However, it seems that at times, I will encounter issue where the script still runs but GitRob does not give any output. When I ran the script manually or for the first time, the results are shown. 

I'm thinking of setting up script to restart the gitrob server at daily basis before the script runs. Appreciate the assistance!

**Comment by michenriksen** [comment]
Hi Hanis,

It might be a bit hacky, but a quick shell command like:

    $ ps aux | grep "[g]itrob server" | awk '{print $2}'

will tell you the PID for the gitrob server process currently running. You can then use this in your script to kill it:

    kill `ps aux | grep "[g]itrob server" | awk '{print $2}'`

Hope that helps you. Let me know if you find something out about the root problem though, and I will look into fixing it.
