### ISSUE TITLE
Documentation for gitrob on kali

### ISSUE THREAD

**Issue by jmcgit** [michenriksen/gitrob#9]
You might want to make a note for the installation instructions for kali to install ruby-dev. This is not installed by default and thusly the installation on kali fails with a Gem::Installer::ExtensionBuildError: ERROR. To fix, run apt-get install ruby-dev and gitrob installs without error.

**Comment by michenriksen** [comment]
Hi @jmcgit, what version of Kali are you installing it on? I recently tried installing Gitrob on Kali version `1.0.9a` and actually didn't have to install any packages.

**Comment by jmcgit** [comment]
1.0.6 is the version that I used.

On Sat, Jan 17, 2015 at 6:24 AM, Michael Henriksen <notifications@github.com
> wrote:

> Hi @jmcgit <https://github.com/jmcgit>, what version of Kali are you
> installing it on? I recently tried installing Gitrob on Kali version
> 1.0.9a and actually didn't have to install any packages.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/michenriksen/gitrob/issues/9#issuecomment-70365120>.
>



-- 
---------------------------------------
Jason Coleman
jmcsmtp@gmail.com

**Comment by michenriksen** [comment]
Okay, that is a bit old. I'll close this issue for now as it seems to be an issue on older versions of Kali.
