### ISSUE TITLE
Can't Redo Configuration

### ISSUE THREAD

**Issue by chess1669** [michenriksen/gitrob#90]
Accidentally entered wrong password for gitrob configure. Can not find a way to edit or re submit the credentials. Any ideas?

**Comment by koshtigirish** [comment]
Kill the port number....and try again
If you are using Linux so if port is 9393 then try kill -9 subport

**Comment by bragot** [comment]
For me, the above suggestion didn't work, but what did work for me was to delete the config file and re run gitrob configure

Config file is at ~/.gitrobrc
