### ISSUE TITLE
in `namespace': namespace 'say' is already defined

### ISSUE THREAD

**Issue by root0er** [michenriksen/gitrob#91]
`/home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/github_api-0.14.5/lib/github_api/api.rb:301:in`namespace': namespace 'say' is already defined (ArgumentError)
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/github_api-0.14.5/lib/github_api/client.rb:61:in `<class:Client>'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/github_api-0.14.5/lib/github_api/client.rb:4:in`module:Github'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/github_api-0.14.5/lib/github_api/client.rb:3:in `<top (required)>'
    from /home/root0er/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /home/root0er/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/github_api-0.14.5/lib/github_api.rb:78:in`block in require_all'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/github_api-0.14.5/lib/github_api.rb:77:in `each'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/github_api-0.14.5/lib/github_api.rb:77:in`require_all'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/github_api-0.14.5/lib/github_api.rb:113:in `<module:Github>'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/github_api-0.14.5/lib/github_api.rb:15:in`<top (required)>'
    from /home/root0er/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/root0er/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/gitrob-1.1.0/lib/gitrob.rb:9:in `<top (required)>'
    from /home/root0er/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /home/root0er/.rvm/rubies/ruby-2.0.0-p648/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/gems/gitrob-1.1.0/exe/gitrob:3:in`<top (required)>'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/bin/gitrob:23:in `load'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/bin/gitrob:23:in`<main>'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in `eval'
    from /home/root0er/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:15:in`<main>'
`
what is it? who can help me?

**Comment by koshtigirish** [comment]
Go to client.rb file and comment line number 61 and 62 .it is working for me

**Comment by michenriksen** [comment]
This issue is fixed in version 1.1.1
