### ISSUE TITLE
Accidentally Gave Wrong Hostname to GitRob Configure

### ISSUE THREAD

**Issue by Astrades** [michenriksen/gitrob#97]
I accidentally pressed a button on my keyboard while configuring GitRob and my postgresql server hostname is stuck as the incorrect connection. Every time I try to start GitRob, I am given this error message. 
"
Sequel::DatabaseConnectionError: PG::ConnectionBad: could not translate host name "gitrob" to address: Name or service not known
"
How do I fix/change the hostname I selected to the default value of localhost?
No real issues here with the tool, I just messed it up and wanna know how to fix it. Any opinions/advice?
Thanks for reading.

**Comment by michenriksen** [comment]
Hey there, you can fix it by opening `~/.gitrobrc` in your favourite editor and correct the connection URI. That should make it work again.
